### ISSUE TITLE
Getting "Failed to start ... The filename or extension is too long." when running with gauge-maven-plugin

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-java#103]
_From @olejkavn on July 17, 2017 10:12_

When trying to run my specs with gauge-maven-plugin, I'm getting the following(in terminal):

Failed to start C:\Java\jdk1.8.0_131\jre\bin\java.exe. fork/exec C:\Java\jdk1.8.0_131\jre\bin\java.exe: The filename or extension is too long.
Failed to start gauge API: Runner with pid 5552 quit unexpectedly(exit status 1).

### Versions

* IntelliJ version and edition(Ultimate): 2017.1.5 
* OS information: windows 10
* Gauge IntelliJ plugin version: 0.3.4

```
Gauge version: 0.8.5

Plugins
-------
html-report (4.0.1)
java (0.6.4)

```

Issue connected to limited classpath length on windows OS(my classpath length is 33714 chars)
As workaround I set my user.home variable to "C:\\"(my classpath length was reduced to 28054 chars), but I think it should work without it.

_Copied from original issue: getgauge/Intellij-Plugin#277_

**Comment by BugDiver** [comment]
@olejkavn It doesn't look like an issue with Gauge IntelliJ plugin.
 As per [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath) the MAX_PATH can not be more than 32767.

**Comment by BugDiver** [comment]
_From @olejkavn on July 17, 2017 11:38_

@BugDiver yes, you are right
How I can move this issue to https://github.com/getgauge/gauge-maven-plugin?

**Comment by BugDiver** [comment]
_From @olejkavn on July 17, 2017 11:41_

@BugDiver Also want to say that same issue reproduced whan i'm trying to run specs via  Gauge IntelliJ plugin, I'm sure that plugin should handle such situation without user adjustments

**Comment by BugDiver** [comment]
@olejkavn This issue belongs to [gauge-java](https://github.com/getgauge/gauge-java). @mdolinin has already raised a [PR](https://github.com/getgauge/gauge-java/pull/102) which address this issue but currently it's breaking the builds. We are looking into it.

**Comment by BugDiver** [comment]
Fixed via #102. Should be available in nightly >= 18-7-2017

**Comment by sguptatw** [comment]
@olejkavn - Can you please confirm if this issue is resolved.

**Comment by sguptatw** [comment]
@olejkavn: Closing this issue, as it is resolved. Please feel free to reopen it incase you face the issue again.
