### ISSUE TITLE
Cannot order specs as user needs, it will order according to the alphabetical order

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge-java#109]
### Expected behavior
Specs can be ordered according to the user needs.

### Actual behavior
Specs cannot be re-ordered, it will be ordered according to the alphabetical order.

### Steps to reproduce
1. Create a spec file with the name abc.spec
2. Create a spec file with the name bac.spec
3. Create a spec file with the name cab.spec
4. Now the user cannot run specs according to the order of bac.spec, cab.spec and abc.spec

### Gauge version
Gauge version: 0.9.1

Plugins
-------
html-report (4.0.2)
java (0.6.4)
spectacle (0.1.2)
xml-report (0.2.0)

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge#822

**Comment by sriv** [comment]
Moved since this is relate to Gauge Core.
