### ISSUE TITLE
'Custom messages in reports' works incorrect for multithreading launch (10 - and more)

### ISSUE THREAD

**Issue by sfranchuk** [getgauge/gauge-java#113]
### Expected behavior
'Custom messages in reports' works incorrect for multithreading launch (10 - and more)
For example message for one step, sometimes in a report displayed for another step.
1. Run in multithreading 10 or more specs which use the same step with 'Custom messages'
2. As a result in report step with 'Custom messages' displayed without message, but another step will be have more then one message.

### Gauge version
```
Plugins
-------
html-report (4.0.0)
java (0.6.3)
```

**Comment by nehashri** [comment]
@sfranchuk I am unable to reproduce this bug with a simple project. 
Do make sure that your code is thread safe, such errors usually occur if code is not thread safe.
If you still face the issue with thread safe code, can you share a sample project to reproduce the error.

**Comment by sfranchuk** [comment]
how can i make code thread safe? 
before every scenario created spring context. (one context for one scenario) and as a result `one thread` -> `one scenario` -> `one bean with method`.
```
public class RegisterIoC {

    private ConfigurableApplicationContext context;

    @BeforeScenario
    public void aregisterIoC() {
        context = new SpringApplicationBuilder(ApplicationConfig.class).run();
        ClassInstanceManager.setClassInitializer(context::getBean);
    }

    @AfterScenario
    public void deregisterIoC() {
        ClassInstanceManager.setClassInitializer(null);
        context.close();
    }
}

```

**Comment by zabil** [comment]
Try using [ThreadLocal](https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html)

**Comment by sfranchuk** [comment]
Please close this issue.
Thank you.
