### ISSUE TITLE
@BeforeSpec works incorrectly if spec has a table

### ISSUE THREAD

**Issue by gadgadskiy** [getgauge/gauge-java#114]
this is before spec:
```
@BeforeSpec(tags = "mytag")
public void beforeSpec() {
    createTable(); //creates file testdata/data.csv
}
```
this is spec file:
```
Spec capture
===========================================================
tags: mytag
table:testdata/data.csv

* My before step

Scenario capture
-----------------------------------------------------------

* My step 1 with <Table data>
* My step 2
___________________________________________________________
* My after step
```

### Expected behavior
@BeforeSpec creates a table testdata/data.csv and spec can use it, because it will begin its work after @BeforeSpec will finish.

### Actual behavior
got error:
```
[ParseError] ...my.spec Could not resolve table from table:testdata/data.csv => 'table:testdata/data.csv'
[ParseError] ...my.spec Dynamic parameter <Table data> could not be resolved => 'My step 1 with <Table data>'
```

### Gauge version
`0.9.4`

**Comment by nehashri** [comment]
@gadgadskiy Gauge tries to validate specs before execution. Gauge expects the table csv file to be present at this stage. The `@BeforeSpec` hook is invoked only if the validation passes. Hence, you are getting parse errors as the table could not be resolved. So your method of creating the csv files at the time of execution will not work.

**Comment by gadgadskiy** [comment]
So, isn't any way to create table for spec dynamically? (Now I do it using another spec or main method but it looks like a temporary hack)
(I can't use @BeforeSuite because it doesn't work with tags)
