### ISSUE TITLE
Plugins timing out with the wrong value

### ISSUE THREAD

**Issue by nickmorell** [getgauge/gauge-java#115]
### Expected behavior
Plugin processes should be killed after the time specified by the 'plugin_kill_timeout' property specified in the global gauge.properties file.

### Actual behavior
Plugin is killed after 4 seconds which is the default value. The tests on completion will show this message ' Plugin [Html Report] with pid [7120] did not exit after 4.00 seconds. Forcefully killing it.' however the only things that seem to be not be getting generated are the css and javascript files as I can still browse the report but without any style.

### Steps to reproduce

I am using a Windows machine that is a Slave to a Linux Jenkins master. I have 31 specs with 151 scenarios that take about an hour to an hour and ten minutes to run. The tests are run in parallel with 5 nodes. 

### Gauge version
Gauge version: 0.9.4
Commit Hash: c96bdbb

Plugins
-------
flash (0.0.1)
html-report (4.0.2)
java (0.6.5)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)

**Comment by nehashri** [comment]
@nickmorell The `plugin_kill_timeout` property in gauge.properties seems to work fine. I tried with a huge project on windows and increasing the property seems to fix the ` Plugin [Html Report] with pid [7120] did not exit after 4.00 seconds. Forcefully killing it.` issue.
Can you please make sure that the property is set properly. You can verify that the property is set properly by executing the following command.
```
gauge config plugin_kill_timeout
```
If you are seeing a different timeout than the one you configured, you probably configured it in the wrong place. This can happen if environment variable `GAUGE_HOME` is set to a custom location. If you have set a custom `GAUGE_HOME` property, change the property in `$GAUGE_HOME/config/gauge.properties` file and try again.

**Comment by nickmorell** [comment]
Ok so I ran the command and I got back 30000 which i originally set using gauge config beforehand. However, GAUGE_ROOT did not exist so I point that to %appdata%\gauge and im giving it a try now.

**Comment by nickmorell** [comment]
Test just finished and I still received the same error. It shouldn't matter that the run command is being sent from a Jenkins master server since the gauge.properties file is on the slave server which has the 30000 timeout?

**Comment by nickmorell** [comment]
@nehashri I used the above command and I got back the 30000 value. However, when I checked my system variables I did not have GAUGE_ROOT set. After setting it to %appdata$\gauge it began to work. If this value wasnt set before where was the 4000 value coming from?

**Comment by sriv** [comment]
@nickmorell - gauge falls back to [defaults](https://github.com/getgauge/gauge/blob/master/config/configuration.go#L46) when it does not find the configuration.
