### ISSUE TITLE
Doesn't show custom messages in the html-report in MacOS

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge-java#123]
### Expected: Should be able to see custom messages using gauge plugins for MacOS 
Should be able to see the added custom messages for the html-report when using MacOS

### Actual: Cannot see custom messages using gauge plugins for MacOS 
Cannot see the added custom messages for the html-report when using MacOS

### Steps to reproduce
1. Add a custom message using Gauge.writeMessage("Test");
2. Run the test in Mac machine
3. Open the html-report
4. The custom message won't be visible in that report

### Gauge version
```
Gauge version: 0.9.6

Plugins
-------
html-report (4.0.2)
java (0.6.5)
screenshot (0.0.1)
spectacle (0.1.2)
```

**Comment by sguptatw** [comment]
Working as expected in version
```
Gauge version: 1.0.1.nightly-2018-08-01
Commit Hash: 6aa1ce2

Plugins
-------
java (0.6.9.nightly-2018-07-27)
```
