### ISSUE TITLE
Exception detail message is unavailable in ExecutionContext

### ISSUE THREAD

**Issue by MolineroUA** [getgauge/gauge-java#125]
We are preparing the statistic reports in out test infrastructure, and they contain information about test name, failed step and stack trace is thrown. We get such data from custom hook on `@AfterStep` event. But stack trace is not informative for us, we need to have `detailMessage` from exception as well.

For example,
Test error message from logs:
> Failed Step: Facebook user <username> is created
Specification: specs/services/bonusservice/DailyStoreBonus.spec:11
Error Message: groovy.lang.MissingPropertyException: No such property: bonusType for class: java.lang.String
Stacktrace: 
org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)

Stack trace from `StepDetails`:
> org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)

Could you implement additional field `errorMessage` or store `detailMessage` in addition to stack trace to `stackTrace` in `StepDetails`?

I checked how Gauge handles the tests errors and found that it stores error message and stack trace in different variables:
[https://github.com/getgauge/gauge-java/blob/master/src/main/java/com/thoughtworks/gauge/execution/MethodExecutor.java#L63](url)

and when StepDetails object is creating for ExecutionContext, only stack trace is used:
[https://github.com/getgauge/gauge-java/blob/master/src/main/java/com/thoughtworks/gauge/execution/ExecutionInfoMapper.java#L49](url)

**Comment by BugDiver** [comment]
The issue is fixed through addressed through PR #126. should be available in nightly >= 20-01-2018

**Comment by MolineroUA** [comment]
@BugDiver it looks like we need to regenerate messages in `gauge-java` according to last changes in `gauge-proto`, because the my last commit contains manual change in Messages.java.

**Comment by MolineroUA** [comment]
I checked nightly builds with new changes and it looks like the current issue will be fixed in next release.
Could you please give me some eta for release date?

**Comment by riju91** [comment]
We would have a new release sometime in feb 2018. Thanks

**Comment by MolineroUA** [comment]
Hi, guys! Any updates about release date?

**Comment by BugDiver** [comment]
@MolineroUA  Apologies for the delay. The team is caught in some other things but we will be making a `gauge-java` release in this week.

**Comment by sguptatw** [comment]
**Question**
The stacktrace available is also the truncated one is this the expected behavior?
