### ISSUE TITLE
Gauge is developed on selenium, right? And gauge is supported for IE9?

### ISSUE THREAD

**Issue by Jun12121988** [getgauge/gauge-java#136]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

**Comment by sguptatw** [comment]
Selenium is webdriver. WebDriver is a web automation framework that allows you to execute your tests against different browsers.

Gauge can be integrated with WebDrivers to write tests. 
ex: Selenium, Sahi, [WebDriverIO](http://webdriver.io/) and so on.

So, If Selenium supports the browser you are looking for, you can write webdriver tests for it by using Gauge.

**Comment by Jun12121988** [comment]
thank you very much
