### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by guolongxu** [getgauge/gauge-java#137]
if I enhance (or proxy) the step implemention method ，and throw an RuntimeException，but  now I got an InvocationTargetException from gauge , I hope  gauge show the result is the target Exception not the InvocationTargetException  。how can I do that ?

**Comment by BugDiver** [comment]
@xuguolong2017  Could be please tell us more about the issue, provide the version information of gauge and gauge plugins.

**Comment by jackperalta** [comment]
When I call `gauge init java` and change a method from the step implementation to throw a `RuntimeException`, I get the expected result
```
# Specification Heading
  ## Vowel counts in single word         P F
        Failed Step: The word "gauge" has "3" vowels.
        Specification: specs\example.spec:16
        Error Message: java.lang.RuntimeException: gauge is not a word
        Stacktrace:
        StepImplementation.verifyVowelsCountInWord(StepImplementation.java:23)

  ## Vowel counts in multiple word       P P

Successfully generated html-report to => C:\dev\gauge-test\reports\html-report\index.html
Specifications: 1 executed      0 passed        1 failed        0 skipped
Scenarios:      2 executed      1 passed        1 failed        0 skipped
````
that is with
```
$ gauge -v
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
html-report (4.0.3)
java (0.6.6)
screenshot (0.0.1)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
