### ISSUE TITLE
Ability to register Parameter parsers from User code

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#140]
**Proposed behavior**
Users should be able to register Parameter parsers from user code.

**Suggestion**
* Add an interface for Parameter parser in `gauge-java`
* Any implementations of this interface in user code should be invoked to parse the parameters

**Comment by jackperalta** [comment]
this interface is already available https://github.com/getgauge/gauge-java/blob/6b6dfcfb72aa977357810181608d45ed9745fe2f/src/main/java/com/thoughtworks/gauge/execution/parameters/parsers/base/ParameterParser.java. 

Though is there a reason, it is not type parameterized ? 
Like
```
public interface ParameterParser<T> {
    T parse(Class<T> parameterType, Parameter parameter) throws ParsingException;
}
```

The main question for this is then, how to change the current hard wired loading of all parsers in https://github.com/getgauge/gauge-java/blob/6b6dfcfb72aa977357810181608d45ed9745fe2f/src/main/java/com/thoughtworks/gauge/execution/parameters/parsers/base/ParameterParsingChain.java to a dynamic one, where it is guaranteed that the user implementation is added first in the chain

**Comment by sguptatw** [comment]
**Test Case**
- Use a custom parameter and generate step implementation. The name generated must be independent of the value user has provided.
- Getting a null pointer exception if the parser is implemented in a default package - https://github.com/getgauge/gauge-java/issues/142

**Comment by sguptatw** [comment]
The performance of step execution had decreased after this change.

**To do**
Test if performance optimization changes  have an impact

**Comment by Apoorva-GA** [comment]
We have pushed a fix for the performance optimisation.
You can check with gauge-java nightly >= 24/04/18
