### ISSUE TITLE
Warnings about illegal access operation occurred

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#149]
**Expected behavior**
Should not get illegal access warnings

**Actual behavior**
Getting the following warnings
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/.../gauge/plugins/java/0.6.7/libs/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future releaseSuccessfully generated html-report to => ...\java1\reports\html-report\index.html
```
**Steps to replicate**
* Create a `gauge-java` project
* Run specs `gauge run specs`
>The above warnings are displayed

**Version**
```
Gauge version: 0.9.8
Commit Hash: c23df9f

Plugins
-------
html-report (4.0.4)
java (0.6.7)
```
JDK 
```
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

**Comment by shubhamsc** [comment]
This seems to be an issue with protobuf library used. There is an [open issue](https://github.com/google/protobuf/issues/3781), which needs a fix in the library.

**Comment by sriv** [comment]
The stacktrace seems to link to selenium and not protobuf. @sguptatw  Do you see this in non-selenium project?

**Comment by nehashri** [comment]
@sguptatw the two issues seem to be completely different looking at the stacktraces given, can we please track them separately.

**Comment by sguptatw** [comment]
As we may have to update dependencies after protobuff changes, we would like to track this. Hence re-opening this.

@sriv @nehashri : Thanks for pointing it out will move it to another card. Will have to check with non-selenium project.

**Comment by ajoecker** [comment]
although a bit old, but the protobuf issue (https://github.com/protocolbuffers/protobuf/issues/3781) has been recently fixed.

And @sguptatw you can run Gauge with Java 10. This is my default setup with Gauge/Selenium

**Comment by Apoorva-GA** [comment]
@ajoecker Thanks for pointing protobuf issue fix, we noticed that too. 
We are waiting for their latest release with the above fix.

**Comment by Debashis9012** [comment]
Able to replicate it with the fix version. 
``` 20-3-2019 ```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed. Tested with the below version
``` nightly-2019-03-24 ```
