### ISSUE TITLE
Unable to determine if a test is running in parallel or not

### ISSUE THREAD

**Issue by andrew041** [getgauge/gauge-java#154]
### Expected behavior
Gauge-Java should have a couple variables added to ExecutionContext that states if an execution is running in parallel, how many nodes are executing, and how many were specified.

### Actual behavior
Without some nasty work-arounds, this is not possible to determine.

### Steps to reproduce
N/A

### Gauge version
v0.9.7+

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
