### ISSUE TITLE
Remove Junit dependency

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-java#155]
### Current behavior
Gauge java plugin and templates bundle JUnit but only uses the assertion library.

### Expected behavior
Bundle only an assertion framework preferably [Assert4J](https://joel-costigliola.github.io/assertj/)

**Comment by ajoecker** [comment]
when I run `mvn clean install archetype:integration-test` is it safe to say that the classes also compile ? or is it a simple comparison of acutal and expected ?

**Comment by BugDiver** [comment]
@ajoecker  Yes, It will compile the classes. Since `compile` phase is before `install` phase in the maven build lifecycle, It will compile all classes. Refer https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Build_Lifecycle_Basics

**Comment by ajoecker** [comment]
but this is the case for classes in the src/main/java folder, right ? Here there are somewhere in the resource folder.

And if I dliberately type in an error, it only complains that they are not equal, but no compilation error occurs.

The background question here is, how can I ensure that my removal of the junit dependency and the introduction of assertJ is rigt ?

**Comment by Apoorva-GA** [comment]
Should be available in gauge-java nightly >= 04/06/18

**Comment by sguptatw** [comment]
The gauge-maven projects created in IDE using the latest archetypes still contain the junit dependency org.assertj.

**Comment by sguptatw** [comment]
The gauge-maven projects created still contain the junit dependency.

**Steps to replicate**
* Create a gauge-maven project`gauge init java_maven`
* Open it in IDE, maven imports all the dependencies
* In the external libraries section Maven: junit is still available

**Version**
```
Gauge version: 0.9.9.nightly-2018-06-01
Commit Hash: 812f26e

Plugins
-------
java (0.6.9.nightly-2018-06-06)
```
This is the same behavior when project is created using Archetype - gauge-archetype-java and gauge-archetype-selenium LATEST in the IDE

**Comment by sguptatw** [comment]
The above issue occurs because 
```
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.0.1</version>
            <scope>test</scope>
        </dependency>
```
Including this in the pom adds the junit dependency. Since this is a 3rd party dependency, closing this issue.
