### ISSUE TITLE
Allow multiple packages to be defined with `package_to_scan` env var

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-java#161]
**Current Behaviour**
To optimize the classes scanned to find all steps, hooks etc, we have a environment variable called `package_to_scan`. This takes only one value right now. 

**Expected Behaviour**
`package_to_scan` should take multiple values.

**Comment by nehashri** [comment]
should be available in nightly >= 06-06-2018

**Comment by ajoecker** [comment]
just found this now - cannot find documentation about the variable - is there any ?

Does the variable accept packnames or also wildcards ? So would `com.mydomain.*` be valid and scan all subpackages of `com.mydomain` ?

**Comment by nehashri** [comment]
@ajoecker It looks like this feature was implemented already. However there seems to be some issues related to this, they are referenced above.

The current implementation is that, `package_to_scan` environment variable can be specified, it can take a comma separated list of packages. If a package is specified, it should scan all its subpackages as well.
For example, `package_to_scan = com.thoughtworks` effectively returns URLs from the classpath containing packages starting with `com.thoughtworks`.
For now, we don't allow wildcards here.
