### ISSUE TITLE
Ability to register Step Exception Handler from User code

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [getgauge/gauge-java#162]
### Proposed behavior
Ability to register Step Exception Handler from User code
### Suggestion
- Add an interface for Step Exception Handler in gauge-java
- Any implementations of this interface in user code should be invoked to handle the step exception
- user can deal with the exception or just throw it

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
