### ISSUE TITLE
Ability to get current step text with values of dynamic parameters from ExecutionContext

### ISSUE THREAD

**Issue by MolineroUA** [getgauge/gauge-java#166]
### Expected behavior
Tester should be able to get current step text with values of dynamic parameters from ExecutionContext.

### Actual behavior
When step parameters are dynamic, the method ExecutionContext.getCurrentStep().getText() returns step text with placeholders, for example "User <username> logged-in from client <clientTypeName>"

### Steps to reproduce
1. run test with step which receives dynamic parameters
2. get step text from ExecutionContext on AfterStep or BeforeStep event 

### Gauge version
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
html-report (4.0.3)
java (0.6.8)
screenshot (0.0.1)
xml-report (0.2.0)

#165

**Comment by sguptatw** [comment]
**Open Question**
What should be the behavior for file/table parameters?

**Comment by MolineroUA** [comment]
@sguptatw 
for table the param **dynamicText** will contain a step text from spec with replacements for placeholders
for example:

> |machineName|
> |Pink Panther   |
>
> OpenMachine
> ----------------
> * User opens video slots machine \<machineName\>

the dynamic text will look like 

> User opens video slots machine "Pink Panther"

**Comment by sriv** [comment]
If the question is for something like this:

`* Step that takes a <table:foo.csv>`

I think the `dynamicText` should inline the csv as text, formatted. Just like the output you'd see if you did a `table.toString` in the implementation and write to console.

**Comment by sguptatw** [comment]
@MolineroUA : Thank you for the clarification. I am rephrasing the question - What should be the behavior for special parameters like <file:somethin.txt> and <table:foo.csv>
@sriv Clarified regarding the special parameter table.

Currently file parameter <file:...> gives the path of the file. 
Given that the value being passed to the step is the content of the file and not the file path. Should this value be available in dynamic Text?

We are playing a story https://github.com/getgauge/gauge/issues/1006 where the special parameter file is available as a table value. What should be the behavior?

**Comment by MolineroUA** [comment]
@sguptatw 
for my opinion, in case of feature https://github.com/getgauge/gauge/issues/1006, dynamic text should contain the file content. 

As I see in the ticket we have the step to reproduce "Inside that table pass a file to read it as a string".

So, if we have the next table

> |param1 | param2                  |
> | value1  | <file:somefile.txt> |
> * Get \<param1\> and \<param2\>

and **somefile.txt** contents the string **value2**
the dynamic text should be **Get "value1" and "value2"**
