### ISSUE TITLE
Should be able to run specs after configuring package_to_scan

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#167]
**Actual behavior**
When package_to_scan is specified, the step implementations are not recongnized

**Steps to replicate**
* Create a gauge-maven project
`gauge init java_maven`
> with group id grp1
* The default package is grp1
* Now add a package grp2 at the same level as grp1
* Add a package level2 inside grp2
* Create a class inside grp2.level2
```
package grp2.level2;

import com.thoughtworks.gauge.Step;
import com.thoughtworks.gauge.Table;
import com.thoughtworks.gauge.TableRow;

import java.util.HashSet;

import static org.assertj.core.api.Assertions.assertThat;

public class StepImplementation {

    @Step("Something")
    public void implementation1() {

    }
}
```
* Use step "Something" in example.spec
* Run the spec `example.spec` from the IDE.
> Execution is successful
* Add `package_to_scan=grp1,grp2.level2`
* Re-load the project
* Execute the same spec
> During validation the steps are marked as unimplemented

**Version**
```
Gauge version: 0.9.9.nightly-2018-06-01
Commit Hash: 812f26e

Plugins
-------
java (0.6.9.nightly-2018-06-06)
```
Related to https://github.com/getgauge/gauge-java/issues/161

**Comment by nehashri** [comment]
Seems to be working fine. 
Check if you have added the correct nightly version of gauge-java in the pom.xml as well.

**Comment by sguptatw** [comment]
Working as expected with
```
Gauge version: 1.0.1.nightly-2018-06-19
Commit Hash: 583ef1d

Plugins
-------
java (0.6.9.nightly-2018-06-12)
```
Re-load after making the following pom changes.
```
 <repositories>
        <repository>
            <id>maven-gauge-java</id>
            <url>https://dl.bintray.com/gauge/maven-gauge-java</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>com.thoughtworks.gauge</groupId>
            <artifactId>gauge-java</artifactId>
            <version>0.6.9.nightly-2018-06-12</version>
            <scope>test</scope>
        </dependency>
...
    </dependencies>
```
