### ISSUE TITLE
CSV file path can be able to define in the environment property files.

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge-java#180]
### CSV file path can be able to define in the environment property files.
I need to set `table: path_to_csv` as environment specific.
The requirement is to validate 3 different data sets in dev, qa and uat environments.
If I can set the path_to_csv inside of the environment property files, would be ideal.

### CSV file path cannot define in the environment property files.
I cannot define `path_to_csv` inside environment property file (default.properties) and reference it in the spec file.

### Gauge version
```
Gauge version: 1.0.1.nightly-2018-07-12
Commit Hash: ef40517

Plugins
-------
flash (0.0.1)
html-report (4.0.4)
java (0.6.8)
json-report (0.2.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by zabil** [comment]
Unfortunately csv files must be loaded while parsing the spec files and must be deterministic. The workaround is generating a csv file based on the environment to the location referred to in the spec before running gauge tests.
