### ISSUE TITLE
Is it possible to have shared step implementations?

### ISSUE THREAD

**Issue by bkim54** [getgauge/gauge-java#186]
I was wondering if it was possible to create an artifact that would contain common step implementations that would be used in multiple scenarios across different projects and use them inside each project's gauge test?

**Comment by NivedhaSenthil** [comment]
There is no straight forward way to share step implementations across projects. The step implementation path should be relative to project root.

**Comment by NivedhaSenthil** [comment]
@bkim54 my bad, you can add the path of artefacts to the property `gauge_additional_libs` in `env/default/java.properties`

**Comment by sriv** [comment]
adding on to @NivedhaSenthil - you should be able to create a jar with step implementations and share it across multiple gauge projects. Gauge should scan the path in `gauge_additional_libs` and use the implementations.

**Comment by bkim54** [comment]
thanks will give it a shot!

I was also wondering if there was any support or examples of using gauge with sbt and scala?
