### ISSUE TITLE
Any support for scala?

### ISSUE THREAD

**Issue by bkim54** [getgauge/gauge-java#187]
Is there any support or examples to run gauge implementations in scala?

**Comment by sriv** [comment]
Not directly, there was a similar request to support clojure a while back.

But you might be able to get the execution bit working (not authoring). See the example for groovy here: https://github.com/getgauge-examples/groovy-selenium

If you get your scala code to build into a jar, you might be able to get gauge-java to read and execute implementations.

Note: this is purely coincidental, and we don't test out multiple jvm languages. I guess the fact that all JVM based languages compile to the same bytecode helps this case.

**Comment by shubhamsc** [comment]
Currently, gauge doesn't have any support with scala. You can follow the above instruction to execute scala code.
> If you get your scala code to build into a jar, you might be able to get gauge-java to read and execute implementations.

I'm closing this issue. If you have any question you can ask in gitter(https://gitter.im/getgauge/chat)
