### ISSUE TITLE
Include a reference to the `Throwable` in `StepDetails`

### ISSUE THREAD

**Issue by glalejos** [getgauge/gauge-java#189]
### Expected behavior
The `StepDetails` passed via `ExecutionContext` of an `@AfterStep` method should contain a direct reference to the `Throwable` that made the step fail.

### Actual behavior
Only pre-formatted exception information is available. Particularly, there is no information about nested exceptions.

### Steps to reproduce
1. Run a test that throws any exception.
2. Only the description of the outer exception is included, with only two lines of stacktrace.

### Gauge version
```
Gauge version: 1.0.1
Commit Hash: da2676b

Plugins
-------
html-report (4.0.5)
java (0.6.8)
screenshot (0.0.1)
```

**Comment by glalejos** [comment]
#146

**Comment by glalejos** [comment]
#162

**Comment by BugDiver** [comment]
@glalejos The verbosity of the stack trace was reduced as part of https://github.com/getgauge/gauge-java/issues/108.
As you have alreay pointed out there are some open issues around it. Example: #146.
Althought the #162 is a different issue. 

Would you please add your usecase/suggestions to the respective issue?

I'm closing this issues as I feel it's a duplicate of #146. Please feel free to add your thoughts.

**Comment by glalejos** [comment]
That's fine @BugDiver. I'll update #146. Thanks.
