### ISSUE TITLE
To create an executable jar from a gauge -java project for transferring the project to docker

### ISSUE THREAD

**Issue by KarthikaPrem** [getgauge/gauge-java#217]
I am working on a project with selenium java with maven and framework used is gauge framework. Can anyone suggest me an idea to convert my entire project into an executable jar so that I can copy my entire project with all the dependencies to docker. 

I tried creating a single jar using this maven assembly plugin, but I faced an issue here. While executing the jar-with-dependencies, it is not identifying the @step annotations present in the step implementation class files. I am getting an error as 'step implementation not found' though all the implementations are present in the class files in 'target/classes' folder

**Comment by KarthikaPrem** [comment]
Does anyone of you has an idea on this? If so please help me to figure it out.

**Comment by sriv** [comment]
Hi @KarthikaPrem  - I _think_ I understand your requirement,feel free to discard if I haven't. There are two approaches I've seen to run a gauge-java project in docker:

1) use a docker base image with jdk etc installed, and build and run the gauge-java project within the image. 
2) if you wish to copy a pre-compiled jar/classes, you could copy it to the docker container and do one of the below:
  a. copying class files - set the location in `gauge_custom_build_path`. this also signals gauge-java to not build the project.
  b. copy the jar with the step implementation to a directory and set the path in`gauge_additional_libs` property.

Note: both `gauge_custom_build_path` and `gauge_additional_libs` can be set via environment variable, so you could potentially build a docker image with the values set and volume mount the directory from host.

ref: https://docs.gauge.org/latest/configuration.html#java-properties-1

Does this help?

**Comment by BugDiver** [comment]
We hope the @sriv's comments help. Closing it, for now, please feel free to reopen it if needed.
