### ISSUE TITLE
Getting Gauge server crash message after compilation error correction

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#219]
**Expected behavior**
Should be able to continue after making changes in source code

**Actual behavior**
Getting Gauge server crashed error

**Steps to replicate**
* Open project in VSCode
[new_java.zip](https://github.com/getgauge/gauge-java/files/2711391/new_java.zip)
> This project has a compilation error on line:16 of StepImplementation.java
* Open the spec file. CodeLens do not appear
* Open the log you will see the compilation error details
* Open `StepImplementation.java`. Correct the compilation error. Make the variable name `someOtherString` to `vowelString`.
* Save the file
* Open the spec file
> The codeLens still does not appear. In the meanwhile the Gauge crash message is displayed

**Version**
```
Gauge version: 1.0.4.nightly-2018-12-25
Commit Hash: fe5e7da

Plugins
-------
java (0.7.0.nightly-2018-12-20)
```

> Blocks #https://github.com/getgauge/gauge-vscode/issues/83

**Comment by BugDiver** [comment]
The issue here is the vscode extension is not setting the SHOULD_BUILD_PROJECT for normal java projects.

**Comment by BugDiver** [comment]
This issue was moved to getgauge/gauge-vscode#322
