### ISSUE TITLE
Cannot get "Tags" in Gauge when running using maven command 

### ISSUE THREAD

**Issue by sudhuhegde** [getgauge/gauge-java#223]
### Expected behavior

Inside the BeforeSuite we should be able to get what tags we are running

### Actual behavior

We are unable to get

### Steps to reproduce
1. Run gauge using "mvn test-compile gauge:execute -DspecsDir=specs -Dtags='Sanity'" 
2. Try to get tags using System.getenv("tags")  

### Gauge version
Gauge version: 1.0.3

Plugins
-------
html-report (4.0.6)
java (0.6.9)

**Comment by haroon-sheikh** [comment]
@sudhuhegde You cannot do `System.getenv("tags")` as -Dtags is not set as an environment variable. There isn't a way to get that property at the moment.

If you're looking to just get current tags, you can have something like this:

```java
@BeforeSpec
    public void getTags(ExecutionContext context) {
        System.out.println(context.getCurrentScenario().getTags());
        System.out.println(context.getCurrentSpecification().getTags());
    }
```

Or more about it here https://docs.gauge.org/latest/writing-specifications.html#current-execution-context-in-the-hook

**Comment by sudhuhegde** [comment]
@haroon-sheikh  
Currently we have separate report dashboard for Sanity and Regression tests . I need post the test results to correct dashboard depending on the  my test suite. If my test suite is Sanity then I have to send reports to Sanity Dashboard otherwise to regression.
Since I execute the test using these command "mvn test-compile gauge:execute -DspecsDir=specs -Dtags='Sanity'"  is there I can achieve the above ?

**Comment by haroon-sheikh** [comment]
I would recommend using `ExecutionContext` for getting tags.

However, you can also specify an environment variable that will achieve what you're trying to do.

E.g. `tags=Sanity mvn test-compile gauge:execute -DspecsDir=specs -Dtags=$tags` and then you can do your normal `System.getenv("tags")`.

**Comment by sudhuhegde** [comment]
Thanks @haroon-sheikh

**Comment by sriv** [comment]
@sudhuhegde - if this is sorted, then can I close the issue?

**Comment by ajoecker** [comment]
i guess this is related to https://github.com/getgauge/gauge/issues/1333

**Comment by haroon-sheikh** [comment]
Yep, i agree. @sudhuhegde was able to workaround for now.
