### ISSUE TITLE
Release Tasks 0.7.0

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-java#224]
These are the release activities to be performed when releasing Gauge java.

## Pre release
- [x] Check all commits that has been added with this release and make sure the relevant issues are tested/closed.
- [x] Check if all relevant tests(FTs and LSP tests on gocd, travis) are passing
- [x] Check compatibility of plugin with gauge and other plugins. Make sure gauge/other plugins are released if needed
- [x] Take a call on release.

## Release 
- [x] Trigger the java-deploy pipeline
- [x] Make a note of all external contributors and add thank you note in release notes
- [x] Review the release notes and publish it.
- [x] Make changes to gauge-repository with latest version details.

## Post release
- [x] Check if the latest version of the plugin is shown for `gauge update -c` command
- [ ] Send release mail to google groups
- [x] Bump up plugin version for further development

**Comment by BugDiver** [comment]
This release has some issues. The release has been reverted. We won't be sending google group emails.
