### ISSUE TITLE
Expose api so writeMessage does not create a message in a new line

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge-java#23]
Expose APIs similar to java's **print()** and **println()** so that a user can control if the messages go into a new line on the report.

**Comment by osandadeshan** [comment]
Actually this is a very good suggestion. I also try to print a table as a custom message inside the report by using the System.out.println() output way. It failed in styling. Hope you guys make this happen.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
