### ISSUE TITLE
Version 0.7.0 breaks ioc-spring plugin example - Error Message: java.lang.NoSuchMethodException: com.thoughtworks.gauge.example.java.PaymentService.<init>()

### ISSUE THREAD

**Issue by BenjaminHerbert** [getgauge/gauge-java#230]
I am facing issues regarding the latest 0.7.0 gauge-java together and the ioc-spring example:
https://github.com/getgauge-examples/ioc-spring

Checkout the example, update the gauge-java version to 0.7.0 and run `mvn test`

### Expected behavior

The build should work complete without error

### Actual behavior

The build fails, with this error message:

<pre>
[INFO] --- gauge-maven-plugin:1.3.4:execute (default) @ gaugeWithSpring ---
Installing required plugins.
.....................
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/travis/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Using com.thoughtworks.gauge.example.java.RegisterIOC as class initializer
# Payment Service
  ## Successfull payment	 ✔WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
 ✘
        Failed Step: Pay amount "500" rupees
        Specification: specs/paymentService.spec:8
        Error Message: java.lang.NoSuchMethodException: com.thoughtworks.gauge.example.java.PaymentService.<init>()
        Stacktrace: 
        java.base/java.lang.Class.getConstructor0(Class.java:3302)
        java.base/java.lang.Class.newInstance(Class.java:532)
        com.thoughtworks.gauge.DefaultClassInitializer.initialize(DefaultClassInitializer.java:22)
        com.thoughtworks.gauge.ClassInstanceManager.get(ClassInstanceManager.java:39)
        com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:37)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:76)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:69)
        com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:51)
        com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
        com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:43)
        com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:29)
        com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:48)
        com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:93)
        com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:115)
        com.thoughtworks.gauge.GaugeRuntime.lambda$connectSynchronously$1(GaugeRuntime.java:98)
        java.base/java.lang.Thread.run(Thread.java:844)
        
  ## Unsuccessful payment	 ✔ ✘
        Failed Step: Fail to pay "2000" rupees
        Specification: specs/paymentService.spec:13
        Error Message: java.lang.NoSuchMethodException: com.thoughtworks.gauge.example.java.PaymentService.<init>()
        Stacktrace: 
        java.base/java.lang.Class.getConstructor0(Class.java:3302)
        java.base/java.lang.Class.newInstance(Class.java:532)
        com.thoughtworks.gauge.DefaultClassInitializer.initialize(DefaultClassInitializer.java:22)
        com.thoughtworks.gauge.ClassInstanceManager.get(ClassInstanceManager.java:39)
        com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:37)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:76)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:69)
        com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:51)
        com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
        com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:43)
        com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:29)
        com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:48)
        com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:93)
        com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:115)
        com.thoughtworks.gauge.GaugeRuntime.lambda$connectSynchronously$1(GaugeRuntime.java:98)
        java.base/java.lang.Thread.run(Thread.java:844)
</pre>

### Steps to reproduce

* Checkout the example, update the gauge-java version to 0.7.0 and run `mvn test`
* alternative: https://github.com/getgauge-examples/ioc-spring/pull/2 (see [Pull-Request](https://github.com/getgauge-examples/ioc-spring/pull/2))

### Gauge version
```
gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.6)
java (0.7.0)
screenshot (0.0.1)
xml-report (0.2.1)
```

**Comment by Debashis9012** [comment]
This issue has been fixed.
Version:

```
Gauge version: 1.0.5.nightly-2019-02-08
Commit Hash: 6971850

Plugins
-------
dotnet (0.1.1.nightly-2019-01-29)
html-report (4.0.7.nightly-2019-01-11)
java (0.7.1.nightly-2019-02-08)
```
