### ISSUE TITLE
Version 0.7.0 breaks multiple directories for gauge_custom_compile_dir

### ISSUE THREAD

**Issue by smathistad** [getgauge/gauge-java#231]
### Expected behavior
Successful validation with multiple directories specified for the `gauge_custom_compile_dir` parameter in java.properties file.

### Actual behavior
During validation getting the following exception
`java.nio.file.NoSuchFileException: /sub/work/Project/../subProj1/src,../subProj2/src`

### Steps to reproduce
Specify multiple directories for the `gauge_custom_compile_dir` parameter in java.properties file.
 For example, our parameter is similar to this: 
`gauge_custom_compile_dir = ../subProj1/src,../subProj2/src`

Note that the java.properties file says they should be separated by a comma
```
# specify the directory containing java files to be compiled
# you can specify multiple directory names separated with a comma (,)
gauge_custom_compile_dir = 
```
Then, run any gauge spec.

### Gauge version
```
C:\dev>gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
html-report (4.0.6)
java (0.7.0)
json-report (0.2.2)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

```

**Comment by smathistad** [comment]
I don't think this is in the nightly build mentioned above.  I am still getting the NoSuchFileException.
Also, when IntelliJ decompiles the jar file, it still shows the ";"
![image](https://user-images.githubusercontent.com/16822234/52137261-c56b0180-260f-11e9-86db-d4b2f9dc1d09.png)

**Comment by nehashri** [comment]
@smathistad you are right, the nightly date was wrong. You should be able to see the fix in nightly >= 04-02-2019

**Comment by Debashis9012** [comment]
Able to validate successfully with multiple directories which has been defined `gauge_custom_compile_dir` parameter under java.properties file.

Version:
`Gauge version: 1.0.5.nightly-2019-02-04
Commit Hash: 06ce0f6

Plugins
-------
html-report (4.0.7.nightly-2019-01-11)
java (0.7.1.nightly-2019-02-04)
`
