### ISSUE TITLE
0.7.0 - throws a GaugeRuntime exception when running in parallel

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge-java#232]
Running the existing tests in parallel with 0.7.0 throws the following exception and works fine on 0.6.9

### Actual behavior
```bash
jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:38)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:76)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:69)
com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:51)
com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:43)
com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:29)
com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:48)
com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:93)
com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:115)
com.thoughtworks.gauge.GaugeRuntime.lambda$connectSynchronously$1(GaugeRuntime.java:98)
java.base/java.lang.Thread.run(Thread.java:834)
19:38:42.526 
```

### Gauge version
```
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.6)
java (0.7.0)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

**Comment by negiDharmendra** [comment]
@haroon-sheikh I am on java 1.8.0_181

**Comment by haroon-sheikh** [comment]
@negiDharmendra I'm seeing this on on java9 and java11.

**Comment by negiDharmendra** [comment]
@haroon-sheikh I am not able to reproduce the issue on java11. I would be helpful if you can point me to the location to download Java9. 
Can you share a sample project with us where this issue is reproducible?

**Comment by haroon-sheikh** [comment]
@negiDharmendra I'm not really sure whats causing this so can't create a sample project.

After a bit of digging, its throwing this error:
```
Invalid message type received ExecutionEnding
```
https://github.com/getgauge/gauge-java/blob/d6118fa7ac8ea176a6345d0ee35fd1f6822f58e7/src/main/java/com/thoughtworks/gauge/connection/MessageDispatcher.java#L91

**Comment by haroon-sheikh** [comment]
After further investigation, the above error only thrown when `enable_multithreading` is set to `true`.

**Comment by negiDharmendra** [comment]
@haroon-sheikh Still no luck in reproducing the error. Please try with the [latest](https://bintray.com/gauge/gauge-java/Nightly/0.7.1.nightly-2019-01-30) nightly.

**Comment by haroon-sheikh** [comment]
@negiDharmendra Is that stacktrace in https://github.com/getgauge/gauge/issues/1338 any helpful?

**Comment by BugDiver** [comment]
@haroon-sheikh A new version of `gauge-java` has been released. Please update the same and check if it fixes your issue.

**Comment by haroon-sheikh** [comment]
@BugDiver @negiDharmendra I cannot reproduce the issue on `0.7.1` 👍 Happy to close the issue for now. Thanks.
