### ISSUE TITLE
Composed step names doesn't work anymore

### ISSUE THREAD

**Issue by DaSwedishMan** [getgauge/gauge-java#235]
### Expected behavior
Gauge should find composed step names.

### Actual behavior
Since updating java-plugin from 0.6.8 to 0.7.0 gauge complains about missing step implementations.

### Steps to reproduce
1. Create the example project with 'gauge init java'
2. In StepImplementation.java change the line:
`    @Step("The word <word> has <expectedCount> vowels.")`
to:
`    @Step("The" + " word <word> has <expectedCount> vowels.")`

### Gauge version
> 
> Gauge version: 1.0.4
> 
> Plugins
> -------
> flash (0.0.1)
> html-report (4.0.6)
> java (0.7.0)
> screenshot (0.0.1)
> spectacle (0.1.3)
> xml-report (0.2.1)

**Comment by Debashis9012** [comment]
Composed steps working properly. Tested with the below version

```
Gauge version: 1.0.5.nightly-2019-02-06
Commit Hash: 3bb3fb0

Plugins
-------
html-report (4.0.7.nightly-2019-01-11)
java (0.7.1.nightly-2019-02-07)
```
