### ISSUE TITLE
BeforeSpec and AfterSpec called on different instances?

### ISSUE THREAD

**Issue by samfoo** [getgauge/gauge-java#24]
I have a use case that requires a consistent connection for each step, and for that connection to live for the life of the spec. The obvious approach of having the connection be a part of the step implementation as an instance variable seems to cause problems since `@BeforeSpec` and `@AfterSpec` get called on different instances.

Due to upstream library dependencies, the connection MUST be closed or it caused all sorts of problems/race-conditions.

1. This seems like the wrong behaviour. The principle of least astonishment would lead me to believe that they'd be called on the same instance.
2. Is there another way to accomplish this use case without using a static/threadlocal that I'm not understanding?

Example:

```java
    @BeforeSpec
    public void connectToMainframe() throws Exception {
        this.mainframe = Mainframe.connectTo("<host>", 30072);
    }

    @AfterSpec
    public void disconnectFromMainframe() throws Exception {
        this.mainframe.disconnect();
    }
```

**Comment by ApoorvaM** [comment]
By default, Gauge clears all the objects that are created after each scenario. But, this is configurable in env/default/java.properties file of your project. Here is more details on [how you can set this at various levels](http://getgauge.io/documentation/user/current/test_code/java/configuration.html#gauge_clear_state_level).

By setting `gauge_clear_state_level`, this can be configured. 

When this is set to `spec`, it means that the `@BeforeSpec` hook, the spec execution and `@AfterSpec` hook are all called on same instance. After this, it clears all the objects in cache and creates new objects for next spec execution. 

This can also be set to `suite` level which allows same objects to be used throughout the suite execution.

Please let us know if I dint get your question right.

**Comment by mahendrakariya** [comment]
Hi @samfoo,
Are you still facing this issue?

**Comment by samfoo** [comment]
I haven't tried changing the configuration via properties. I think not having it work on the same instance by default violates the principle of least astonishment. I've sorted out the issue for the time being, though.

**Comment by mahendrakariya** [comment]
@samfoo Do you have any updates on this?

**Comment by bkim54** [comment]
@mahendrakariya I changed the properties file and it worked for me! thanks!

**Comment by apoorvam** [comment]
Cool, Closing this for now. Feel free to reopen if needed.
