### ISSUE TITLE
gauge install java is not install gauge java plugin

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge-java#245]
### Expected behavior
`gauge install java` should install gauge java plugin

### Actual behavior
`gauge install java` is not install gauge java plugin and throw the below error.
```
Failed to install plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.
Failed to install plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.
```

### Screenshot:
![image](https://user-images.githubusercontent.com/9147189/53014040-40844280-346d-11e9-9915-f720655b6fd2.png)

### Steps to reproduce
1. Pre Requisites: Windows 10 64 bit, Already installed gauge 1.0.1 and plugins
2. Install gauge by (`choco install gauge`)
3. Run this command to install java plugin `gauge install java` or update java plugin `gauge update java` 

I have removed gauge java plugin and again try with the 3rd step. But the same error is there.

### Gauge version
```
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
flash (0.0.1)
html-report (4.0.2)
json-report (0.2.2)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.0)
```

**Comment by negiDharmendra** [comment]
@osandadeshan Please run this command `gauge config --list` and send the details to us.

**Comment by osandadeshan** [comment]
C:\Users\Osanda Deshan\AppData\Roaming\gauge\plugins>gauge config --list
Key                             Value
----------------------------------------------------------------------
gauge_repository_url            https://downloads.getgauge.io/plugin
gauge_update_url                https://downloads.getgauge.io/gauge
plugin_kill_timeout             4000
ide_request_timeout             30000
gauge_telemetry_action_recorded true
gauge_templates_url             https://downloads.getgauge.io/templates
runner_connection_timeout       30000
plugin_connection_timeout       10000
runner_request_timeout          30000
check_updates                   true
gauge_telemetry_enabled         false
gauge_telemetry_log_enabled     false

**Comment by negiDharmendra** [comment]
@osandadeshan There was an SSL certificate issue with `gauge_repository_url` which has been resolved now. Please try installing again and let us know if you face the same issue again.

**Comment by ajoecker** [comment]
can confirm that it works

```
$ gauge install java
........................
Successfully installed plugin 'java'.
```

**Comment by osandadeshan** [comment]
@negiDharmendra @ajoecker 
Yes gauge java language runner is now successfully installing.
Thanks.

**Comment by solomkinmv** [comment]
Hi, I have the same problem as @osandadeshan.

```
 ❯ gauge install java                                               
Failed to install plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.
Failed to install plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.%

 ❯ gauge -v
Gauge version: 1.0.4

Plugins
-------
No plugins found
Plugins can be installed with `gauge install {plugin-name}`

 ❯ gauge config --list                                               
Key                           	Value
-------------------------------------------------------------------
ide_request_timeout           	30000
check_updates                 	true
gauge_telemetry_action_recorded	true
gauge_update_url              	https://downloads.gauge.org/gauge
gauge_templates_url           	https://templates.gauge.org
plugin_connection_timeout     	10000
plugin_kill_timeout           	4000
gauge_telemetry_log_enabled   	false
gauge_repository_url          	https://downloads.gauge.org/plugin
runner_connection_timeout     	30000
runner_request_timeout        	30000
gauge_telemetry_enabled       	false
```

Can you suggest something?

**Comment by NivedhaSenthil** [comment]
https://downloads.gauge.org/plugin is down, we will be fixing that soon.

**Comment by NivedhaSenthil** [comment]
@solomkinmv can you please try again and see if it works now ?

**Comment by solomkinmv** [comment]
@NivedhaSenthil now it works for me

**Comment by Yashk-12** [comment]
Am also facing same problem cant install java...This error is coming after running my project
 Failed to get configuration from Gauge properties file. Error: open C:\Program Files\Gauge\bin\config\gauge.properties: The system cannot find the path specified.
Compatible version of plugin java not found. Installing plugin java...

**Comment by Yashk-12** [comment]
@NivedhaSenthil Can you please help me to solve it

**Comment by zabil** [comment]
@Yashk-12 can you please tell

* When you started seeing this error?
* Which versions of Gauge and Java are you using?
* Steps along with the Gauge command that led to this error?
