### ISSUE TITLE
Refactoring doesn't return proper step implementation parameters

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-java#255]
While refactoring the param names generated is not consistent. The refactoring should return consistent parameter values. 
For more details check https://build.gauge.org/go/tab/build/detail/Java-LSP-Tests/103/wd/1/linux.

**Comment by Debashis9012** [comment]
Tested with the below version its working as excepted.

``` gauge-1.0.5.nightly-2019-03-19 ```
