### ISSUE TITLE
[JDK-12]: Getting illegal warnings in maven project

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-java#258]
**Excepted Result:** 
Should not get illegal access warnings

**Actual Result**
Getting below warnings
``` 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/C:/Users/Debas/.m2/repository/com/google/pro
tobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
**Steps to reproduce**
1. Create `gauge init java_maven` project
2. run ``` mvn test ```
3. Observe warnings in console output

**Tested version**
Gauge version: 1.0.5.nightly-2019-03-20
Commit Hash: 7aaf683

Plugins
-------
csharp (0.10.6.nightly-2019-03-12)
dotnet (0.1.1)
html-report (4.0.8.nightly-2019-03-08)
java (0.7.2.nightly-2019-03-24)

**Comment by Apoorva-GA** [comment]
Issue is not replicable with the above mentioned versions.

**Comment by Debashis9012** [comment]
Reproducible in the below version:

```
Gauge version: 1.0.4
Plugins
-------
java (0.7.1) 
```

**Comment by Apoorva-GA** [comment]
The issue is not replicable in the latest release of java `0.7.2`.

**Comment by Debashis9012** [comment]
works fine with ``` java (0.7.3.nightly-2019-04-01) ```
