### ISSUE TITLE
Default src directory is scanned regardless of property gauge_custom_compile_dir

### ISSUE THREAD

**Issue by vngthb** [getgauge/gauge-java#260]
Issue is based on a question addressed in the gitter chat, quoted:

> For the Java runner, there's a constant called "DEFAULT_SRC_DIR", is there any particular reason to why it is hardcoded and not configurable from a property?
> 
> It kinda ruins the point of property "gauge_custom_compile_dir", as when I try to manually select the packages I want to be loaded (e.g. specific step implementations), the "src" dir is automatically thrown in the list of directories that will get scanned, resulting with all the step implementations getting scanned anyway.
> 
> Given this I've been wondering if there's a particular reason to why it is implemented like this? Would it be possible to have an option that would let us decide whether we want the "src" dir to get loaded or not at least?
> 
> Thanks. ;)

### Expected behavior
If property **gauge_custom_compile_dir** is set then the default src directory should not be added to the list of directories that would get scanned for step implementations. 

### Actual behavior
Regardless of the property **gauge_custom_compile_dir**, directory src is added to the list of directories that will get scanned for step implementations.
(Please check the attached images for a better understanding of the issue)

### Steps to reproduce
Will add if they will be required alongside with a project where it can be easily reproduced.

### Gauge version
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
html-report (4.0.3)
java (0.7.2)
screenshot (0.0.1)
spectacle (0.1.2)

![gauge custom complire directories issue](https://user-images.githubusercontent.com/49160802/55482958-448bae80-562e-11e9-8c38-dd052e88a416.jpg)
![gauge issue cause](https://user-images.githubusercontent.com/49160802/55482959-448bae80-562e-11e9-9a99-42085ec804f6.jpg)

**Comment by BugDiver** [comment]
@vngthb This definitely seems to be a bug. We will be fixing it soon.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the below version:
``` java (0.7.3.nightly-2019-04-10) ```
