### ISSUE TITLE
Add ability to access Table cell by column name

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-java#28]
Say one has a table:

Foo | Bar | Baz
------|------|------
x  | y | z
a  | b | c

One should then be able to get the values from a row by specifying the column name.

Ex:

```
<datatype?> row = table.GetRows()[0];
// row["Foo"] should get x
```

Pick a datatype for `Row` that would allow this.

Deprecate `row[0]` style index based accessors, since this would be error prone when using large tables.

**Comment by apoorvam** [comment]
This can now be accessed as :
```
for (TableRow tableRow : table.getTableRows()) {
     System.out.println(tableRow.getCell("Product"));
}
```
