### ISSUE TITLE
[Feature Request] Allow loading a file from classpath in spec definition

### ISSUE THREAD

**Issue by ajoecker** [getgauge/gauge-java#301]
### Expected behavior
In a Java project allow to define a special parameter `classpath` to load files from classpath.

### Background
In java projects (mainly in maven/gradle projects), the structure of resources that are used in a project are defined (`src/test/resources`). It would be beneficial to allow the path to a resource in the spec instead of given the full path.

So instead of  `<file:src/test/resources/myfile.txt>` something like `<classpath:myfile.txt>`

**Comment by zabil** [comment]
This can be considered while implementing https://github.com/getgauge/gauge/issues/94
