### ISSUE TITLE
[ValidationError] in multi-module Java project

### ISSUE THREAD

**Issue by sxexesx** [getgauge/gauge-java#307]
### Expected behavior
User should be able to run specs from different modules

### Actual behavior
Recognize an error:

```TestMavenModule/specs
[ValidationError] C:\Users\sxexesx\GaugeTestRun\TestMavenModule\specs\example.spec:10 Step implementation not found => 'Vowels in English language are "aeiou".'
[ValidationError] C:\Users\sxexesx\GaugeTestRun\TestMavenModule\specs\example.spec:15 Step implementation not found => 'The word "gauge" has "3" vowels.'
Add the following missing implementations to fix Step implementation not found errors.
```

### Steps to reproduce
1. create a project with module TestMavenModule
2. console command: gauge java init
3. add maven and guage build plugin, parent dependencies to pom-file (you can check simple project here: [GitHubProject here](https://github.com/sxexesx/GaugeTestRun)  )
4. execute from command line: 
`mvn gauge:execute -f pom.xml -DspecsDir=TestMavenModule/specs -Denv="default"`
5. watch an error

INFO:
Test works well in Intellij IDEA without error.
Test finishes succeful with mvn-build-tool but with error in the begining.
Probably, this issue links with [bug](https://github.com/getgauge/gauge-java/issues/279)

### Gauge version
```
Gauge version: 1.0.0

Plugins
-------
html-report (4.0.5)
java (0.7.2)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by negiDharmendra** [comment]
@sxexesx  Please change 
`mvn gauge:execute -f pom.xml -DspecsDir=TestMavenModule/specs -Denv="default"` 
to 
`mvn gauge:execute -f TestMavenModule/pom.xml -DspecsDir=TestMavenModule/specs -Denv="default"`

**Comment by sxexesx** [comment]
It works! Thank you!
