### ISSUE TITLE
Remove golang dependency

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-java#324]
We currently use go to build and run the plugin. 
We use make.go file to build and run tests. 
We use gauge-java.go file to build a binary which in turn runs the java project.
Remove these dependencies.
Use maven tasks to run tests and build the plugin.
The gauge-java plugin should be started with java command itself or shell scripts.

**Comment by BugDiver** [comment]
## Things needs to be tested

- [ ] Should be able to build project locally without Golang 
- [ ] Should able to create an offline project with newly installed gauge-java plugin
- [ ] Should able to run project with newly installed gauge-java plugin
- [ ] Should able to run maven project with newly installed gauge-java plugin
- [ ] Should able to run gradle project with newly installed gauge-java plugin
- [ ] Should able to run project from IDEA with newly installed gauge-java plugin
- [ ] Should able to run project with properties like, `package_to_scan, gauge_custom_classpath, gauge_custom_build_dir, gauge_jvm_args` etc.

**Comment by Debashis9012** [comment]
verified and tested.
`f4d95ac131724bf631e7b1d95182c7fbae9a6ee7`
