### ISSUE TITLE
gauge run having only fat .jar file and specs folder

### ISSUE THREAD

**Issue by raducrisan1** [getgauge/gauge-java#331]
### Expected behavior

I have created a Docker image that has gauge installed and java plugin enabled. I also added the fat .jar file that contains step implementations. 
I mounted a volume with the specs folder and I want to run 'gauge run specs/' and my specs to be executed

Is there any way to run specs without deploying the source code of the steps implementation ?

### Actual behavior
gauge cli returns 'Failed to find project directory'

### Steps to reproduce
I will simplify by avoiding docker this time; will use a temporary folder instead of a docker container.

1. Create a gauge project with gauge init java_gradle and add some steps implementation
2. run gradle assemble and copy the build/libs/*.jar into a ~/tmp/test folder
3. copy specs folder into ~/tmp/test folder
4. cd ~/tmp/test and run 'gauge run specs/'

### Gauge version
```
1.0.7
```

**Comment by nehashri** [comment]
@raducrisan1 For a folder to be recognized as a Gauge test folder, you should not only copy over the specs folder. The `manifest.json` file is needed for Gauge to find out which plugins and language runner to use. The `env` folder is required too. Along with that, you may have to put your jar file in the libs directory, for it to be found by Gauge. Refer https://docs.gauge.org/configuration.html?language=java#language-plugin-configurations for any configurations that you may need to do.

**Comment by negiDharmendra** [comment]
@raducrisan1 Any update on this?
