### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shanzee05** [getgauge/gauge-java#339]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x88b16d]

goroutine 110 [running]:
github.com/getgauge/gauge/runner.(*LanguageRunner).EnsureConnected(0xc00032f920, 0x30)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/runner/runner.go:232 +0x14d
github.com/getgauge/gauge/runner.(*LanguageRunner).ExecuteAndGetStatus(0xc00032f920, 0xc00037c840, 0x2e)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/runner/runner.go:287 +0x2f
github.com/getgauge/gauge/runner.(*MultithreadedRunner).ExecuteAndGetStatus(0xc000264260, 0xc00037c840, 0x1)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/runner/runner.go:128 +0x38
github.com/getgauge/gauge/execution.executeHook(0xc00037c840, 0xc744c0, 0xc0002e0cb0, 0xc8b1c0, 0xc000264260, 0xc0003ea420)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:403 +0x3b
github.com/getgauge/gauge/execution.(*stepExecutor).notifyAfterStepHook(0xc00032f110, 0xc0002e0cb0)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/stepExecutor.go:100 +0xa8
github.com/getgauge/gauge/execution.(*stepExecutor).executeStep(0xc00032f110, 0xc00017af00, 0xc00045e6c0, 0x0)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/stepExecutor.go:64 +0x33b
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeStep(0xc0003e8070, 0xc00017af00, 0xc0003fe000, 0xc0002bb980, 0xc000260000)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:175 +0x19a
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeSteps(0xc0003e8070, 0xc0002556e0, 0x6, 0x6, 0xc000255710, 0x6, 0x6, 0xc0002bb980)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:153 +0xa8
github.com/getgauge/gauge/execution.(*scenarioExecutor).execute(0xc0003e8070, 0xc745e0, 0xc0001071e0, 0xc8be80, 0xc0002bb980)
[INFO] ------------------------------------------------------------------------
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/scenarioExecutor.go:87 +0x912
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
github.com/getgauge/gauge/execution.(*specExecutor).executeScenario(0xc0001af3e0, 0xc0001071e0, 0xc0002642a0, 0x0, 0x1)
[INFO] Total time:  05:51 min
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:317 +0x26e
[INFO] Finished at: 2019-12-26T13:15:32Z
github.com/getgauge/gauge/execution.(*specExecutor).executeScenarios(0xc0001af3e0, 0xc0002642a0, 0x1, 0x1, 0xc0002642a0, 0x1, 0x1, 0xc000264298, 0x1)
[INFO] ------------------------------------------------------------------------
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:274 +0x83
github.com/getgauge/gauge/execution.(*specExecutor).executeSpec(0xc0001af3e0, 0xc0001078c0, 0xc00045e180)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:160 +0x11b
github.com/getgauge/gauge/execution.(*specExecutor).execute(0xc0001af3e0, 0x10101, 0xc000264260)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/specExecutor.go:129 +0x930
github.com/getgauge/gauge/execution.(*simpleExecution).executeSpecs(0xc0003ee070, 0xc000254d50, 0xc0003a0240, 0x0, 0x0)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/simpleExecution.go:130 +0x193
[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.3.3:execute (default-cli) on project assignment-test: Gauge Specs execution failed. null: GaugeExecutionFailedException -> [Help 1]
github.com/getgauge/gauge/execution.(*simpleExecution).execute(0xc0003ee070)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/simpleExecution.go:92 +0x185
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.3.3:execute (default-cli) on project assignment-test: Gauge Specs execution failed. null
github.com/getgauge/gauge/execution.(*parallelExecution).startSpecsExecutionWithRunner(0xc00018b0e0, 0xc000254d50, 0xc000390000, 0xc8b1c0, 0xc000264260, 0x6)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/parallelExecution.go:240 +0x9e
github.com/getgauge/gauge/execution.(*parallelExecution).startMultithreaded(0xc00018b0e0, 0xc8b1c0, 0xc000264260, 0xc000390000, 0x6)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/parallelExecution.go:198 +0x88
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
created by github.com/getgauge/gauge/execution.(*parallelExecution).executeMultithreaded
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/execution/parallelExecution.go:189 +0x5c6

Scenario : Multi threaded Java Gauge  . Total 20 test in 7 parallel stream one of the  test takes 5 min which fails after that  I get Gauge crash

**Comment by negiDharmendra** [comment]
@shanzee05 We will need more information to replicate the issue.

- run `gauge -v` on your terminal and share the output with us
- which os you are working on

**Comment by sriv** [comment]
Closing this. Please comment when you get more information for us to help troubleshoot.
