### ISSUE TITLE
Custom screenshot Grabber takes blank screenshot 

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-java#348]
### Expected behavior
On failure, custom screenshot grabber should take the correct screenshot.

### Actual behavior
It always attaches the empty screen under ./gauge/screenshot and inside the html-report.

### Steps to reproduce
1. unzip the below attached java_maven_selenium project
2. execute the script: `mvn test`

[testArti.zip](https://github.com/getgauge/gauge-java/files/4045385/testArti.zip)

### Gauge version
```
Gauge version: 1.0.7
Commit Hash: cc341c44

Plugins
-------
flash (0.0.1)
html-report (4.0.9)
java (0.7.4)
js (2.3.7)
json-report (0.3.2)
python (0.3.8)
ruby (0.5.3)
screenshot (0.0.1)
spectacle (0.1.3)
```

**Comment by nehashri** [comment]
This seems to be an issue with the implementation. 
The implementation is not correct in the gauge docs.

**Comment by negiDharmendra** [comment]
Sample custome screenshot grabber class

**CustomScreenshotGrabber.java**
```
import com.thoughtworks.gauge.screenshot.ICustomScreenshotGrabber;

import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;

import driver.Driver;

public class CustomScreenshotGrabber implements ICustomScreenshotGrabber {
    public byte[] takeScreenshot() {
        return  ((TakesScreenshot) Driver.webDriver).getScreenshotAs(OutputType.BYTES);
    }
}
```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
