### ISSUE TITLE
Maven project with Gauge - Step implementation can not be found if it has args

### ISSUE THREAD

**Issue by SeleniumTestAB** [getgauge/gauge-java#349]
### Expected behavior
When in Maven project there is Spec file containing steps with arguments and proper Step class the Spec file should find those steps.

### Actual behavior
The Inteliji marks step implementation in Step class as incorrect (as if proper implementation does not exist because step have args)

### Steps to reproduce
1. Create Maven project and set Gauge in it
2. Create example.spec that has step with args
3. Create Step implementation
4. Try to run gauge

### Gauge version
```
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
java (0.7.3)
json-report (0.3.2)
screenshot (0.0.1)
xml-report (0.2.2)

```

**Comment by negiDharmendra** [comment]
@SeleniumTestAB Are you facing the same issue with deafault Gauge Java maven project.
run `gauge init java_maven` to create a sample maven project.

**Comment by SeleniumTestAB** [comment]
@negiDharmendra I did, and still issue is present. It can be problem with Inteliji plugin for gauge. Is there any update coming?

**Comment by ajoecker** [comment]
I do not quite understand your problem.

Given a step in a spec that contains two parameters, it does not find the matching implementation ? or what ?

![2020-01-15 08_40_34-nexible-pricing  C__Users_ajoecker_dev_nexible-automated-tests  -  _frontend-s](https://user-images.githubusercontent.com/36064843/72414602-e9691980-3772-11ea-8db8-cf6888719f03.png)
 
which is fine for me. 

```
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
java (0.7.2)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```
with IntelliJ Gauge plugin `0.3.18`

**Comment by SeleniumTestAB** [comment]
@ajoecker indeed. In my case the step in spec and step implementation in class (i speak only for example spec btw) are marked by inteliji that they have error. In spec error says that it can not find step implementation and in example step class the error is that step method should not have arguments. Furthermore, when i try to gwnerate step implementation from spec it doesnt do it.

**Comment by SeleniumTestAB** [comment]
P. S. You use different version of gauge and java than I. So could you make this check on the newest version?

**Comment by negiDharmendra** [comment]
@SeleniumTestAB Are you able to run gauge specs from command line?

**Comment by SeleniumTestAB** [comment]
@negiDharmendra i did but then gauge did not recognize additional libs that i added to my pom(which is why i try to use java_maven).

**Comment by negiDharmendra** [comment]
@SeleniumTestAB are you able run gauge specs using maven from command line.

**Comment by SeleniumTestAB** [comment]
@negiDharmendra i did but then gauge did not recognize additional libs that i added to my pom(which is why i try to use java_maven).

**Comment by SeleniumTestAB** [comment]
I did test that and it finally worked. I first run command gauge init java_maven, then used mvn clean install and then with Inteliji i added some dependencies and run mvn clean install from IDE level and it works fine now. Thanks for help.
