### ISSUE TITLE
Unable to capture screenshots if screenshot_on_failure is set to false

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-java#350]
**Expected Behaviour**
Custom screenshot should be captured even if screenshot_on_failure is set to false.

**Actual Behaviour**
Screenshot is not captured.

**Steps to Reproduce**
* Initialise a java project.
* Set the `screenshot_on_failure = false` in default.properties file.
* In a step implementation, try to capture custom screenshot by using `Gauge.captureScreenshot();`.
* Run the gauge project.
* An error is thrown by html-report with `Failed to read screenhsot read <dir>/.gauge/screenshots: is a directory`. 
The screenshot directory is empty after executing the program.

**Comment by Debashis9012** [comment]
Verified and found fixed.
