### ISSUE TITLE
Failed to start gauge API: fork/exec bin/gauge-java: bad CPU type in executable

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge-java#352]
Since the upgrade to macOS Catalina, running gauge throws:

### Actual behavior
Error ----------------------------------

[Gauge]
`Failed to start gauge API: fork/exec bin/gauge-java: bad CPU type in executable`

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
        darwin, 1.0.6
        flash (0.0.1), html-report (4.0.8), java (0.7.2), js (2.3.5), reportserver (0.1.1), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.1)

### Steps to reproduce
1. gauge run specs/

### Gauge version

```
Gauge version: 1.0.6

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
java (0.7.2)
js (2.3.5)
reportserver (0.1.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

**Comment by BugDiver** [comment]
@haroon-sheikh Can you make sure you have installed the right plugin (darwin-64)?
The reason I'm asking is macOS Catalina does not let 32-bit apps. So if you have mistakenly installed the 32 bit It will not work.

I'm working on macOS Catalina an I do not see this issue with a 64-bit plugin.
In case you have installed the right plugin and still, it does not work, maybe give us a little more details like
How did you installed gauge and plugins, or any other environment-specific details which you think might be the reason for the issue?

**Comment by haroon-sheikh** [comment]
After the upgrade to Catalina caused the errors above. Uninstalling and installing all plugins agains fixed the issue.
