### ISSUE TITLE
Execution hooks should be run in some order, not random

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge-java#36]
If there is more than one `@BeforeScenario` hook, they are executed in random order. They could be executed in order as : 
* Hooks which are not tagged : These are generic hooks which applies to all scenarios/specs. An analogy would be the base class setup of any unit test framework.
* Hooks which are tagged : These are hooks which are specific to use case. 

If there is more than one hook in any of the above category, hooks will be sorted based on method names and executed in that order.

**Comment by Thunderforge** [comment]
I think that additional Javadoc is needed in `@BeforeScenario`, describing the ordering behavior (e.g. tagged vs untagged, sorted by method name).

Also, does this apply to other annotations too, such as `@AfterScenario`?

**Comment by apoorvam** [comment]
Yes. It is applicable to Execution hooks at all levels. 

You are right. We should be adding this as part of javadocs.

**Comment by apoorvam** [comment]
The hooks such as @AfterScenario(post hooks) will be executed in exactly reverse order as that of 
@BeforeScenario hooks.
```
BeforeScenario With no tags
       BeforeScenario with Tags
              Scenario
       AfterScenario with Tags
AfterScenario with no tags
```
