### ISSUE TITLE
Failed to start gauge API: Timed out connecting to java

### ISSUE THREAD

**Issue by coding-lama** [getgauge/gauge-java#368]
After updating gauge to version 1.0.7 and updating gauge-java to 0.7.4 and html-report to 4.0.9, I am unable to run my tests. 

### Expected behavior
Run all tests, and produce report

### Actual behavior
I get the following error
```
specifications-executed_1 | > Task :gauge
specifications-executed_1 | 
specifications-executed_1 | Error ----------------------------------
specifications-executed_1 | 
specifications-executed_1 | [Gauge]
specifications-executed_1 | Failed to start gauge API: Timed out connecting to java
specifications-executed_1 | 
specifications-executed_1 | Your Environment Information -----------
specifications-executed_1 | 	linux, 1.0.7, ed7b4fd6
specifications-executed_1 | 	html-report (4.0.9), java (0.7.4), screenshot (0.0.1)
specifications-executed_1 | 
specifications-executed_1 | > Task :gauge FAILED
specifications-executed_1 | 
specifications-executed_1 | FAILURE: Build failed with an exception.
specifications-executed_1 | 
specifications-executed_1 | * What went wrong:
specifications-executed_1 | Execution failed for task ‘:gauge’.
specifications-executed_1 | > Execution failed for one or more tests!
specifications-executed_1 | 
specifications-executed_1 | BUILD FAILED in 1m 26s
specifications-executed_1 | 4 actionable tasks: 4 executed
specifications_specifications-executed_1 exited with code 1
Aborting on container exit...
```

### Gauge version
```
specifications-executed_1  | Gauge details:
specifications-executed_1  | Gauge version: 1.0.7
specifications-executed_1  | Commit Hash: ed7b4fd6
specifications-executed_1  | 
specifications-executed_1  | Plugins
specifications-executed_1  | -------
specifications-executed_1  | html-report (4.0.9)
specifications-executed_1  | java (0.7.4)
specifications-executed_1  | screenshot (0.0.1)
```

**Comment by cyberjaime45** [comment]
Having a same issue, Had to went back to Gauge version: 1.0.5

**Comment by zabil** [comment]
@cyberjaime45 @coding-lama Can one you please help in debugging this? Will appreciate it a lot if you can follow the steps in https://github.com/getgauge/gauge/issues/1380#issuecomment-585721962 to send some logs. 

Please make sure the logs don't have any confidential info.

**Comment by sriv** [comment]
hi @coding-lama and @cyberjaime45 - please can you check if your `build.gradle` points to the `0.7.4` version of `gauge-java`? It should look something like:

```
...
dependencies {
   ...
   implementation 'com.thoughtworks.gauge:gauge-java:0.7.4'
   ...
}
...
```

**Comment by coding-lama** [comment]
@sriv yes, I had there ```compile "com.thoughtworks.gauge:gauge-java:0.6.9"```

I changed it to ```compile "com.thoughtworks.gauge:gauge-java:0.7.4"```

However after build attempt, it says  ```Could not resolve: com.thoughtworks.gauge:gauge-java:0.7.4```

**Comment by sriv** [comment]
@coding-lama - are you seeing the error in a fresh project as well? Or have you noticed it only when upgrading?

**Comment by coding-lama** [comment]
> @coding-lama - are you seeing the error in a fresh project as well? Or have you noticed it only when upgrading?

Since I am working on existing project only, so  during the upgrade only.

**Comment by negiDharmendra** [comment]
@coding-lama Is it possible for you to share a sample project to reproduce this issue? It will be a greate help to debug and resolve this issue.

**Comment by haroon-sheikh** [comment]
@negiDharmendra You can use this https://github.com/getgauge/gauge/issues/1581 to reproduce.

**Comment by negiDharmendra** [comment]
> I changed it to compile "com.thoughtworks.gauge:gauge-java:0.7.4" however now it skips all implemented test, as "implementation not found"

@coding-lama If your implementaions are inside the `src/main/java` then please try setting `gauge_custom_compile_dir` env varible in `<project-path>/env/default/java.properties` to `src/main/java`

**Comment by apurva94** [comment]
+1

**Comment by sriv** [comment]
@negiDharmendra put an issue with possible things to look at: https://github.com/getgauge/gauge-java/issues/377#issue-567501356

please check the below:
- gauge version should be `1.0.7`
- gauge-java (plugin) version should be `0.7.4`
- gauge-java(dependency) version should be `0.7.4` (this could be in your `pom.xml` or `build.gradle` files)

The above will ensure that the latest (as of date) versions of all components are in place. Also make a note to clean and compile.

**Comment by coding-lama** [comment]
> > I changed it to compile "com.thoughtworks.gauge:gauge-java:0.7.4" however now it skips all implemented test, as "implementation not found"
> 
> @coding-lama If your implementaions are inside the `src/main/java` then please try setting `gauge_custom_compile_dir` env varible in `<project-path>/env/default/java.properties` to `src/main/java`

@negiDharmendra the thing is I am using kotlin to implement the specs, the implementation in my project is in "src/test/kotlin"  
Its looks like gauge is looking for implementation in "src/main/java"; I know this because I am getting the following error:

```
/Users/.../src/test/java
java.nio.file.NoSuchFileException: /Users/.../src/test/java
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
        at java.base/java.nio.file.Files.walk(Files.java:3820)
        at java.base/java.nio.file.Files.walk(Files.java:3874)
        at com.thoughtworks.gauge.FileHelper.lambda$getAllImplementationFiles$1(FileHelper.java:40)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at com.thoughtworks.gauge.FileHelper.getAllImplementationFiles(FileHelper.java:39)
        at com.thoughtworks.gauge.scan.StaticScanner.addStepsToRegistry(StaticScanner.java:80)
        at com.thoughtworks.gauge.command.StartCommand.execute(StartCommand.java:19)
        at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:18)
```
Then I see Validation Errors on all of the specs i have already implemented.

I also tried to set the gauge_custom_compile_dir parameter to pit to my implementation folder to "src/test/kotlin", the above mentioned error is not displayed, however the Validation Errors remain.

**Comment by NivedhaSenthil** [comment]
@coding-lama  Thanks for digging up and giving more relevant details I could replicate the issue with step implementations written in kotlin, we will be fixing this soon

**Comment by NivedhaSenthil** [comment]
closing this to merge all kotlin related issues in #390
