### ISSUE TITLE
Refactoring fails with message "Refactoring failed: null"

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge-java#37]
**Step** : 
`In an empty directory initialize a project with the current language`

**method** : 

```
@Step({"In an empty directory initialize a project with the current language"})
public void initializeProject() throws Exception {
}
```

Gauge-java is not handling the case where array with 1 step text (`{"In an empty directory initialize a project with the current language"}`)  is passed to `@Step` annotation.

**Comment by Apoorva-GA** [comment]
Refactoring a step with alias is not supported but if there is only one value in alias then refactoring should be successful. 

@sguptatw Please verify.

**Comment by sguptatw** [comment]
This is still replicable
Gauge-IntelliJ Version: 0.3.7.nightly-2017-08-11

**Gauge version**
```
Gauge version: 0.9.2.nightly-2017-08-15

Plugins
-------
csharp (0.10.1)
html-report (4.0.2.nightly-2017-08-07)
java (0.6.5.nightly-2017-08-14)
ruby (0.4.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by Apoorva-GA** [comment]
@sguptatw This works fine with the latest stable versions.

with the nightly version mentioned above this gives an other error
```
Error:Cannot perform refactoring: Unable to connect to runner.Runner with pid 50753 quit unexpectedly(exit status 1).
```
which is being tracked by https://github.com/getgauge/gauge-java/issues/62

Where as it works fine from command line. So issue should be from intelliJ side.

Gauge-IntelliJ Version: 0.3.7.nightly-2017-08-11

Gauge version
-------
Gauge version: 0.9.2.nightly-2017-08-15

Plugins
-------
html-report (4.0.2)
java (0.6.5.nightly-2017-08-14)
spectacle (0.1.2)

**Comment by Apoorva-GA** [comment]
@sguptatw Please try with latest Gauge-IntelliJ nightly  :  0.3.7.nightly-2017-08-18
