### ISSUE TITLE
Cannot run tests after upgrading Gauge version

### ISSUE THREAD

**Issue by Borisakov** [getgauge/gauge-java#372]
### Expected behavior
Tests should run

### Actual behavior
All the running tests are skipped

### Steps to reproduce
1. Upgrade the gauge-java version 
2. Upgrade the gauge version 
3. Upgrade the html-reoprt plugin version 

- All the specs and concepts are getting "[ValidationError]   Step implementation not found => " error
- All the steps in the classes are getting "Add the following missing implementations to fix `Step implementation not found` errors." error

Specifications: 0 executed      0 passed        0 failed        1 skipped
Scenarios:      0 executed      0 passed        0 failed        5 skipped

The runner is Gradle version 1.8.0

### Gauge version
```
Gauge version: 1.0.7

Plugins
-------
html-report (4.0.9)
java (0.7.4)
screenshot (0.0.1)
spectacle (0.1.4)

```

**Comment by sriv** [comment]
hi @Borisakov - if you are using gauge-java 0.7.4 - can you please check if your project uses the same `0.7.4` for gauge-java as it's dependency (either in `pom.xml` or `build.gradle`) ?

**Comment by cyberjaime45** [comment]
I'm having the same issue
https://github.com/getgauge/gauge/issues/1579

**Comment by negiDharmendra** [comment]
@Borisakov If your **implementation** files are not inside `src/test/java` then try setting `gauge_custom_compile_dir` env varible in `<project-path>/env/default/java.properties` to the correct location.

**Comment by Borisakov** [comment]
@sriv I'm using the same version in the runner and in the Gradle dependencies.
@negiDharmendra The files are in src/test/java/.....
I must say that it used to run in the previous version the same way. I didn't change anything.

**Comment by negiDharmendra** [comment]
@Borisakov Is it possible for you to share a sample project where it is reporducible.

**Comment by shanzee05** [comment]
MacBook-Pro:assignment-testing z.akhtar$ mvn gauge:validate -DspecsDir=specs/nightlySpec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building assignment-test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- gauge-maven-plugin:1.4.0:validate (default-cli) @ assignment-test ---
usage: GaugeJava --<start|init>
Error ----------------------------------

[java]
process /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/bin/java with pid 11190 quit unexpectedly. exit status 1

[Gauge]
Failed to start gauge API: Runner with pid 11189 quit unexpectedly(exit status 1)

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
        darwin, 1.0.7
        html-report (4.0.8), java (0.7.3), screenshot (0.0.1)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.392 s
[INFO] Finished at: 2020-02-19T12:13:40+04:00
[INFO] Final Memory: 12M/256M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.thoughtworks.gauge.maven:gauge-maven-plugin:1.4.0:validate (default-cli) on project assignment-test: Gauge Specs execution failed. null: GaugeExecutionFailedException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by shanzee05** [comment]
<dependency>
            <groupId>com.thoughtworks.gauge</groupId>
            <artifactId>gauge-java</artifactId>
            <version>[0.6.8,)</version>
            <scope>test</scope>
        </dependency>

With latest version getting above error -  version 0.7.4
When i change it to  0.7.3  , not getting above error

**Comment by zabil** [comment]
@shanzee05 can you share relevant sections of your pom file configuration?

**Comment by negiDharmendra** [comment]
@shanzee05 Please make sure that the version of Gauge Java installed on the system is similer to the version of Gauge Java dependency mentioned in the pom file.

**Comment by negiDharmendra** [comment]
@shanzee05 This issue happens when install version of Gauge Java is **<= 0.7.3**  and in the **pom.xml** it's 0.7.4

**Comment by Borisakov** [comment]
> @Borisakov Is it possible for you to share a sample project where it is reproducible.
I cannot make it... do you need more details?

**Comment by NivedhaSenthil** [comment]
@Borisakov may we know if you have implementations written in kotlin ? similar issue which we could replicate https://github.com/getgauge/gauge-gradle-plugin/issues/43

**Comment by Borisakov** [comment]
@NivedhaSenthil Yes, my implementations are written in Kotlin.

**Comment by NivedhaSenthil** [comment]
closing this to merge all kotlin related issues in https://github.com/getgauge/gauge-java/issues/390
