### ISSUE TITLE
If you are facing issues after upgrading to the latest version of Gauge 1.0.7 and Java 0.7.4

### ISSUE THREAD

**Issue by negiDharmendra** [getgauge/gauge-java#377]
Here is a list of reasons which might be causing these issues.

 **1.**  If your implementations are inside `src/main/java`

 **Error** - ~~Step implementation not found~~ (Fixed in 0.7.6)
 **Fix** - ~~Set `gauge_custom_compile_dir` env varible in `<project-    path>/env/default/java.properties` to `src/main/java`~~ 

**2.**  Mismatch of  Gauge Java version

run `gauge -v` on your terminal and check the gauge java version 
check your `build.gradle` or `pom.xml` for Gauge Java dependency version and it should match the version mentioned in `gauge -v` output.

**Comment by sriv** [comment]
perhaps this can also be reflected in troubleshooting: https://docs.gauge.org/troubleshooting.html

**Comment by alpha1592** [comment]
HI,

i am getting issues with Step implementation not being found after upgrading to v1.0.7 and 0.7.4 of Gauge Java. 
i added the `gauge_custom_compile_dir` to java.properties but it throws an exception attached below. Most of my steps are in Jar files imported using maven as dependencies. Those are not being picked up at all. In the past, i never had to add the custom compile directory. Everything just worked. 

I really need to upgrade in order to see if the Protobuf issue has been resolved with HTML Report. But this upgrade is causing more serious issues. Please help. 

Exception
```
Testing started at 2:06 PM ...
"C:\Program Files\Gauge\bin\gauge.exe" run --machine-readable --hide-suggestion --simple-console C:/Dexter/demo/demo_tests/specs/Demo.spec:47

C:\Dexter\demo\demo_tests\src\main\java
java.nio.file.NoSuchFileException: C:\Dexter\demo\demo_tests\src\main\java
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3820)
	at java.base/java.nio.file.Files.walk(Files.java:3874)
	at com.thoughtworks.gauge.FileHelper.lambda$getAllImplementationFiles$1(FileHelper.java:40)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.thoughtworks.gauge.FileHelper.getAllImplementationFiles(FileHelper.java:39)
	at com.thoughtworks.gauge.scan.StaticScanner.addStepsToRegistry(StaticScanner.java:80)
	at com.thoughtworks.gauge.command.StartCommand.execute(StartCommand.java:19)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:18)

[ValidationError] C:\Dexter\demo\demo_tests\specs\Demo.spec:50 Step implementation not found => 'Common: Wait for "60" seconds.'


Skipped: Common: Wait for "60" seconds.
Filename: specs\Demo.spec
Message: Step implementation not found


```


Environment Info.
```
--IDE--
IntelliJ v2019.2 Community Edition

--Gauge--
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
flash (0.0.1)
html-report (4.0.9)
java (0.7.4)
json-report (0.3.1)
screenshot (0.0.1)
spectacle (0.1.3)

--Java--
java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)

```

**Comment by sriv** [comment]
Would you be able to share a project that you see this issue with @alpha1592 ?

**Comment by taplar** [comment]
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

Gauge version: 1.0.8
Commit Hash: 28617ea

Plugins
-------
html-report (4.0.10)
java (0.7.6)
json-report (0.3.3)
screenshot (0.0.1)
```

I've upgraded my box to JDK 11 in preparation for upgrading gauge -java to the latest version (due to the deprecation), however I'm running into a different issue than the ones listed in this thread.  As soon as I upgrade from gauge-java `gauge-java-0.7.3-windows.x86_64.zip` to `gauge-java-0.7.4.zip` it appears that gauge stops being able to find our included libraries.  This behavior persists for every version past `0.7.3`, including the latest release.

```
$ gauge run --env st --tags P1
D:\Users\boydma\Repositories\Item\ItemWebFunctional\src\test\java\com\dillards\intranet\item\configurations\FailedTestConfiguration.java:7: error: package org.junit does not exist
import static org.junit.Assert.fail;
^
D:\Users\boydma\Repositories\Item\ItemWebFunctional\src\test\java\com\dillards\intranet\item\configurations\FailedTestConfiguration.java:7: error: static import only from classes and interfaces
import static org.junit.Assert.fail;
^
D:\Users\boydma\Repositories\Item\ItemWebFunctional\src\test\java\com\dillards\intranet\item\utilities\DillardsJsonObject.java:3: error: package org.json.simple does not exist
import org.json.simple.JSONArray;
^
D:\Users\boydma\Repositories\Item\ItemWebFunctional\src\test\java\com\dillards\intranet\item\utilities\DillardsJsonObject.java:4: error: package org.json.simple does not exist
import org.json.simple.JSONObject;
^
D:\Users\boydma\Repositories\Item\ItemWebFunctional\src\test\java\com\dillards\intranet\item\utilities\DillardsJsonObject.java:5: error: package org.json.simple.parser does not exist
import org.json.simple.parser.JSONParser;
...
```

These classes exist in a `libs` directory in the base of the project, and we have them included in our `env/default/java.properties` file with the `gauge_additional_libs`.

```

# Specify an alternate Java home if you want to use a custom version
gauge_java_home =

# IntelliJ and Eclipse out directory will be usually autodetected
# Use the below property if you need to override the build path
gauge_custom_build_path =

# specify the directory where additional libs are kept
# you can specify multiple directory names separated with a comma (,)
gauge_additional_libs = libs/*

# JVM arguments passed to java while launching. Enter multiple values separated by comma (,) eg. Xmx1024m, Xms128m
gauge_jvm_args = -Dwebdriver.chrome.driver=C:/Program Files/Browser Drivers/Chrome Driver/80/chromedriver.exe, -Xms2g, -Xmx2g

#optional D: drive directory when runninn locally
#gauge_jvm_args = -Dwebdriver.chrome.driver=D:/temp/chromedrivers/75.0.3770.8/chromedriver.exe, -Xms4g, -Xmx4g

# specify the directory containing java files to be compiled
# you can specify multiple directory names separated with a comma (,)
gauge_custom_compile_dir =

# specify the level at which the objects should be cleared
# Possible values are suite, spec and scenario. Default value is scenario.
gauge_clear_state_level = spec
```

The same configuration is also present in our environment specific properties file `env/st/user.properties`.

```

# Specify an alternate Java home if you want to use a custom version
gauge_java_home =

# IntelliJ and Eclipse out directory will be usually autodetected
# Use the below property if you need to override the build path
gauge_custom_build_path =

# specify the directory where additional libs are kept
# you can specify multiple directory names separated with a comma (,)
gauge_additional_libs = libs/*

# JVM arguments passed to java while launching. Enter multiple values separated by comma (,) eg. Xmx1024m, Xms128m
gauge_jvm_args = -Dwebdriver.chrome.driver=C:/Program Files/Browser Drivers/Chrome Driver/80/chromedriver.exe, -Xms2g, -Xmx2g

# specify the directory containing java files to be compiled
# you can specify multiple directory names separated with a comma (,)
gauge_custom_compile_dir =

# specify the level at which the objects should be cleared
# Possible values are suite, spec and scenario. Default value is scenario.
gauge_clear_state_level = spec
```

So to reiterate, the project runs the tests with version 0.7.3 and as soon as I upgrade to 0.7.4 the classes not being found starts showing up.

**Comment by BugDiver** [comment]
@taplar We had mistakenly introduced a bug in 0.7.4.  A PR https://github.com/getgauge/gauge-java/pull/419 addressing that issue has been already merged.
We will try to push a release with the fix as soon as possible

**Comment by GedeonNiy** [comment]
Hello,

I am currently using IntelliJ with Java 11. Previously, I was working with Gauge version 1.4.3 and gauge-java 0.7.3, and my specifications were running without any issues. However, following our recent system upgrade from Java 8 to Java 11, we also needed to upgrade Gauge accordingly.

I have attempted to use Gauge version 1.5.6 along with gauge-java 0.10.3 (and other versions beyond 0.7.3 that support Java 11), but I am encountering an issue where all the steps in my specifications are being skipped. The error indicates a missing classpath in the app-gauge directory.

Is there a known solution for this issue? Should any configuration changes be made—perhaps in the manifest file or elsewhere—when upgrading beyond gauge-java 0.7.3?

I would greatly appreciate any guidance or suggestions you can provide.

**Comment by chadlwilson** [comment]
Rather than trying to use old versions you're probably better to try with current gauge and gauge-java versions, since Java 11 is still supported.

As the original issue notes, make sure the plugin version in your test project dependency is the same as the installed plugin.

Also better if you actually include the error rather than referring to a vague classpath issue.

**Comment by GedeonNiy** [comment]
I attached 2 images, one is for the structure of my springboot gradle project which is using java11, specs are in specs folder and the open file is manifest file, and I shared the log I am facing after upgrading gauge to 1.5.6 and gauge-java to 0.10.3, any suggestion of which version combinations I should be using or any config change needed? thanks

<img width="1210" height="867" alt="Image" src="https://github.com/user-attachments/assets/5d8139a5-0d58-411d-b42a-f17c2f52dfde" />
<img width="1736" height="613" alt="Image" src="https://github.com/user-attachments/assets/4f66712a-8df4-44a9-8dd3-505472f14d00" />

**Comment by GedeonNiy** [comment]
Hi,
after restarting my system the error has changed yesterday I was getting all specs skipped errors but now I am getting this : 

<img width="1175" height="293" alt="Image" src="https://github.com/user-attachments/assets/a1e47054-79c4-4694-ab6b-b674c4cca2dd" />

and as you can see I even changed to latest gauge plugin version : 1.6.7 and latest gauge-java version : 0.12.0 .
and it is the same version installed in my system as well as you can see on this screenshot in the build.gralde of my tests-gauge: 

<img width="1021" height="131" alt="Image" src="https://github.com/user-attachments/assets/ba4528e2-b4fc-4377-81e3-9701a6ffc502" /> 

but I tried to run a specs which is not in my system : test1.spec just for test and it is not getting it, which means gauge is entering in my app and face a java Issues that I am not sure why : 

<img width="762" height="53" alt="Image" src="https://github.com/user-attachments/assets/0f5ad2a0-a0b5-40ce-ae6c-99ca4a206629" />

, my system is in java 11 as you can see here : 

<img width="690" height="89" alt="Image" src="https://github.com/user-attachments/assets/4c2a3b69-8405-42ac-abec-8dad1d6a5dad" />


again when I use Gauge version : 1.4.3 with gauge-java : 0.7.3, I am able to run my specs.
I did not changed anything from my application, except changing the gauge-java version in build.gradle and build my gradle springboot app

according to changes came into new gauge versions, what can you recommend me to changes, is the combination I used compatible with java 11?
any combination you can recommend me to use for gauge pluggin and gauge-java version with my java11 system?

thank you

**Comment by GedeonNiy** [comment]
Thanks,

I will try that tomorrow but my question is why it is working fine with old
version of gauge?
Gauge 1.4.3 with gauge-java 0.7.3?

But other versions are failing?

Gedeon NIYONSENGA
***@***.***
972-903-9498
