### ISSUE TITLE
Do not compiling source code it self when incorporates other build processes like Gralde, Maven.

### ISSUE THREAD

**Issue by tan9** [getgauge/gauge-java#40]
I like the format of gauge specification.
But when I try to implement my step using Geb. I found that Gauge Java try to do everything by it self. From source code compiling to spec executing...

Gauge provides Gralde and Maven plugins. However, they all looks like gauge executable invokers. And will not use all existing and de-facto build process. Reflections works on class files, but I just cannot use the Step implementation compiled by Gradle / Maven, because of my source code is not ending with .java? :hushed:

Rename `gauge-java` to `gauge-jvm` just like https://github.com/cucumber/cucumber-jvm maybe a good start?

**Comment by apoorvam** [comment]
@tan9 
Glad to know that you like Gauge spec format. 

We haven't tried using Gauge with Geb. But, you can refer our [Gauge example project with Groovy support](https://github.com/getgauge/gauge-example-groovy). 

If you want to direct Gauge to use already existing class files, you can set custom build path in `env/default/java.properties`. This will not re-compile your source files.
```
# Use the below property if you need to override the build path
gauge_custom_build_path = <path>
```

**Comment by tan9** [comment]
@apoorvam 
Thank you for the groovy example, I will try it out later this week.

**Comment by mahendrakariya** [comment]
@tan9 Do you get time to try out the groovy example?

**Comment by tan9** [comment]
@mahendrakariya , sorry, we later change to development our product using front-end technologies, and adopt the test tools in the box from https://github.com/AngularClass/angular2-webpack-starter .

**Comment by mahendrakariya** [comment]
Cool. I will close the issue.
