### ISSUE TITLE
all SubConns are in TransientFailure, latest connection error: connection error

### ISSUE THREAD

**Issue by jbadeau** [getgauge/gauge-java#409]
### Expected behavior
Tell us what should happen

Running test in

### Actual behavior

[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mgauge-maven-plugin:1.4.2:execute[m [1m(default-cli)[m @ [36mtodo-srv-spec[0;1m ---[m
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[0;36m# Todo
[0m[0;33m  ## Pass	[0mError occurred while waiting for runner process to finish.
Error : exit status 1
[0;31m
        Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:37177: connect: connection refused"
        Stacktrace: 
        
[0m[0;31m
        Failed Step: pass
        Specification: specs/Todo.spec:4
        Error Message: rpc error: code = Unavailable desc = transport is closing
        Stacktrace: 
        
[0m[0;31m
    Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:37177: connect: connection refused"
    Stacktrace: 
    
[0m[0;31m
  Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:37177: connect: connection refused"
  Stacktrace: 
  
[0m
[0m[0;31m
  Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:37177: connect: connection refused"
  Stacktrace: 
  
[0mSuccessfully generated html-report to => /codefresh/volume/mono/apps/todo-srv-spec/reports/html-report/index.html

Failed to kill Runner: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:37177: connect: connection refused"
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

### Steps to reproduce
1. mvn gauge:execute

### OS

Docker base image: maven:3-jdk-11

### Gauge version
```
Gauge version: 1.0.8
Commit Hash: 28617ea

Plugins
-------
html-report (4.0.10)
java (0.7.4)
reportportal (1.2.0)
screenshot (0.0.1)
xray-report (0.1.0)
```

**Comment by jbadeau** [comment]
not reproducible anymore so can close

**Comment by sriv** [comment]
The most common cause for `all SubConns are in TransientFailure` is because the gauge-js runner process quit unexpectedly (could be because of user code, or because of environmental issues).

We will improve the reporting on this.
