### ISSUE TITLE
Broken Java version detection in 0.7.5 on linux

### ISSUE THREAD

**Issue by whipermr5** [getgauge/gauge-java#414]
Gauge-Java 0.7.5 doesn't seem to detect Java version correctly on linux systems, failing with an unsupported Java version error.

### Steps to reproduce
`docker run --rm -it gradle:6.3.0-jdk11 bash -c 'wget -O gauge.zip https://github.com/getgauge/gauge/releases/download/v1.0.8/gauge-1.0.8-linux.x86_64.zip && unzip gauge && ./gauge install java --version 0.7.5 && ./gauge init java && ./gauge run specs'`

### Expected behavior
```
# Specification Heading
  ## Vowel counts in single word	 ✔ ✔
  ## Vowel counts in multiple word	 ✔ ✔
```
(Output of using 0.7.4 instead of 0.7.5 in the docker command above)

### Actual behavior
```
This version of gauge-java plugin does not support Java versions < 1.9
Please upgrade your Java version or use a version of gauge-java <= v0.7.4
Error occurred while waiting for runner process to finish.
Error : exit status 1
Error ----------------------------------

[Gauge]
Failed to start gauge API: Timed out connecting to java
```

### Gauge version
```
Your Environment Information -----------
	linux, 1.0.8, 28617ea
	html-report (4.0.10), java (0.7.5), screenshot (0.0.1)
```
(1.0.8; also not working on 1.0.7)

**Comment by sriv** [comment]
this is caused by a bug in `launcher.sh` which does not handle versions well.

**Comment by sriv** [comment]
@whipermr5 - please try with the latest release - 0.7.6

**Comment by whipermr5** [comment]
@sriv It's working now! Thank you!!
