### ISSUE TITLE
No error when multiple step implementations exist

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge-java#43]
Refer https://github.com/getgauge/gauge-csharp/issues/55

**Comment by mahendrakariya** [comment]
The changes required on Java side are done, thanks to PR #60 by @maquessime. We now need to change Gauge core to identify duplicate step implementation validation error.

**Comment by mahendrakariya** [comment]
Updated proto messages in Gauge core. This is dev complete.

The changes should be available in nightly >= 2016-06-27.

P.S. @sguptatw Please use the nightly >= 2016-06-27 of both Gauge as well as gauge-java for testing this.

**Comment by sguptatw** [comment]
@mahendrakariya : The Gauge nightly 2016-06-27 is not available yet.

**Comment by mahendrakariya** [comment]
It's available now.

**Comment by sguptatw** [comment]
The functionality is working as per the current expectation.
However it will be more useful if the error message had the details of the code files where these duplicate step implementations can be found.
