### ISSUE TITLE
Failed to start gauge API: Timed out connecting to java 

### ISSUE THREAD

**Issue by coding-lama** [getgauge/gauge-java#434]
After upgrading gauge and plugins to latest version, I am unable to run my specifications in docker. I do remove all containers before I use them (fresh start every time) 

### Expected behavior
Gauge should execute all specifications in question

### Actual behavior
specifications-executed_1  | > Task :gauge
specifications-executed_1  | Task ':gauge' is not up-to-date because:
specifications-executed_1  |   Task has failed previously.
specifications-executed_1  | Finished generating test XML results (0.008 secs) into: /specs/build/test-results/gauge
specifications-executed_1  | Generating HTML test report...
specifications-executed_1  | Finished generating test html results (0.06 secs) into: /specs/build/reports/tests/gauge
specifications-executed_1  | Executing command => [gauge, run, --tags, \!temp_disabled,\!failing_needs_to_be_fixed,\!manual_testing_only,\!smoke_test_uat,\!smoke_test_prod, --env, qa, --dir, /specs, --strategy=lazy, --hide-suggestion, specs]
specifications-executed_1  | 2020-05-04 14:43:17:111 INFO Reflections - Reflections took 2708 ms to scan 2 urls, producing 8 keys and 166 values
specifications-executed_1  | Error ----------------------------------
specifications-executed_1  | 
specifications-executed_1  | [Gauge]
specifications-executed_1  | Failed to start gauge API: Timed out connecting to java
specifications-executed_1  | 
specifications-executed_1  | Get Support ----------------------------
specifications-executed_1  | 	Docs:          https://docs.gauge.org
specifications-executed_1  | 	Bugs:          https://github.com/getgauge/gauge/issues
specifications-executed_1  | 	Chat:          https://spectrum.chat/gauge
specifications-executed_1  | 
specifications-executed_1  | Your Environment Information -----------
specifications-executed_1  | 	linux, 1.0.7, ed7b4fd6
specifications-executed_1  | 	html-report (4.0.10), java (0.7.7), screenshot (0.0.1)
specifications-executed_1  | 
specifications-executed_1  | > Task :gauge FAILED
specifications-executed_1  | :gauge (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 32.592 secs.
specifications-executed_1  | 
specifications-executed_1  | FAILURE: Build failed with an exception.
specifications-executed_1  | 
specifications-executed_1  | * What went wrong:
specifications-executed_1  | Execution failed for task ':gauge'.
specifications-executed_1  | > Execution failed for one or more tests!
specifications-executed_1  | 
specifications-executed_1  | * Try:
specifications-executed_1  | Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
specifications-executed_1  | 
specifications-executed_1  | * Get more help at https://help.gradle.org
specifications-executed_1  | 
specifications-executed_1  | BUILD FAILED6 actionable tasks: 6 executed
specifications-executed_1  |  in 2m 58s

### Steps to reproduce
1. Update gauge + plugins
2. update build.gradle file with latest java plugin version
3. run specifications

### Gauge version
```
specifications-executed_1  | Gauge details:
specifications-executed_1  | Gauge version: 1.0.7
specifications-executed_1  | Commit Hash: ed7b4fd6
specifications-executed_1  | 
specifications-executed_1  | Plugins
specifications-executed_1  | -------
specifications-executed_1  | html-report (4.0.10)
specifications-executed_1  | java (0.7.7)
specifications-executed_1  | screenshot (0.0.1)
```

**Comment by sriv** [comment]
Hi - can you try updating gauge to the latest (i.e. 1.0.8)?

I have a demo project, and I added docker build to it, and it works fine.

Project: https://github.com/sriv/gauge-gradle-demo/

Docker action output: https://github.com/sriv/gauge-gradle-demo/runs/645171359?check_suite_focus=true

**Comment by coding-lama** [comment]
Actually, I think the issue might be related to parallel run. I will try with the latest gauge version as suggested

**Comment by coding-lama** [comment]
Hi,

Updated to gauge 1.0.8, gauge-java 0.7.7 and html-report 4.0.10. 
I am able to run a dockerized repository, where I don't utilize selenium/webdriver without any issues. However when I try the same image on a repo with selenium, it gives me the same error... To get more information, I enabled stacktrace option:

specifications-executed_1  | Error ----------------------------------
specifications-executed_1  | 
specifications-executed_1  | [Gauge]
specifications-executed_1  | Failed to start gauge API: Timed out connecting to java
specifications-executed_1  | 
specifications-executed_1  | Get Support ----------------------------
specifications-executed_1  | 	Docs:          https://docs.gauge.org
specifications-executed_1  | 	Bugs:          https://github.com/getgauge/gauge/issues
specifications-executed_1  | 	Chat:          https://spectrum.chat/gauge
specifications-executed_1  | 
specifications-executed_1  | Your Environment Information -----------
specifications-executed_1  | 	linux, 1.0.8, 28617ea
specifications-executed_1  | 	html-report (4.0.10), java (0.7.7), screenshot (0.0.1), spectacle (0.1.4)
specifications-executed_1  | 
specifications-executed_1  | > Task :gauge FAILED
specifications-executed_1  | :gauge (Thread[Execution worker for ':',5,main]) completed. Took 35.164 secs.
specifications-executed_1  | 
specifications-executed_1  | FAILURE: Build failed with an exception.
specifications-executed_1  | 
specifications-executed_1  | * What went wrong:
specifications-executed_1  | Execution failed for task ':gauge'.
specifications-executed_1  | > Execution failed for one or more tests!
specifications-executed_1  | 
specifications-executed_1  | * Try:
specifications-executed_1  | Run with --debug option to get more log output. Run with --scan to get full insights.
specifications-executed_1  | 
specifications-executed_1  | * Exception is:
specifications-executed_1  | org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gauge'.
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
specifications-executed_1  | 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
specifications-executed_1  | 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
specifications-executed_1  | 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
specifications-executed_1  | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
specifications-executed_1  | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
specifications-executed_1  | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
specifications-executed_1  | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
specifications-executed_1  | 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
specifications-executed_1  | 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
specifications-executed_1  | 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
specifications-executed_1  | 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
specifications-executed_1  | 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
specifications-executed_1  | 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
specifications-executed_1  | 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
specifications-executed_1  | 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
specifications-executed_1  | Caused by: com.thoughtworks.gauge.gradle.exception.GaugeExecutionFailedException: Execution failed for one or more tests!
specifications-executed_1  | 	at com.thoughtworks.gauge.gradle.GaugeTask.executeGaugeSpecs(GaugeTask.java:62)
specifications-executed_1  | 	at com.thoughtworks.gauge.gradle.GaugeTask.gauge(GaugeTask.java:51)
specifications-executed_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
specifications-executed_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
specifications-executed_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
specifications-executed_1  | 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
specifications-executed_1  | 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
specifications-executed_1  | 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
specifications-executed_1  | 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
specifications-executed_1  | 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
specifications-executed_1  | 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
specifications-executed_1  | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
specifications-executed_1  | 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
specifications-executed_1  | 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
specifications-executed_1  | 	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
specifications-executed_1  | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
specifications-executed_1  | 	... 34 more
specifications-executed_1  | 
specifications-executed_1  | 
specifications-executed_1  | * Get more help at https://help.gradle.org
specifications-executed_1  | 
specifications-executed_1  | BUILD FAILED in 3m 32s
specifications-executed_1  | 8 actionable tasks: 7 executed, 1 up-to-date

**Comment by zabil** [comment]
> However when I try the same image on a repo with selenium

Do you mean using `gauge init java_maven_selenium`? If not can you share something to replicate this with selenium? It can be something around selenium initialisation and unfortunately the logs provided here does not seem to point to the right issue.

If `gauge init java_maven_selenium` works you can use that as reference to see how to add selenium.

**Comment by coding-lama** [comment]
I have built a docker image which already contains gradle 5.6.4, gauge 1.0.8, gauge-java 0.7.7, html-report 4.0.10 and I am running the specifications in this container. I also have 3 repositories two which automate webpages (using selenium) and one repo which tests an API. The one that tests API and does not utilize selenium/webDriver is working OK with the latest version of gauge and plugins. The other two fail with that error message I shared above.

**Comment by sriv** [comment]
hi @coding-lama - is this still an issue? 

For those projects that have problem running on docker, do you see any errors in `gauge.log`?

**Comment by coding-lama** [comment]
> hi @coding-lama - is this still an issue?
> 
> For those projects that have problem running on docker, do you see any errors in `gauge.log`?

Hi sriv, yes it is still an issue, actually it is the reason why we are still using gauge 1.0.5 and gauge-java 0.7.3 as the newer version are not usable for us until this issue is resolved.

**Comment by sriv** [comment]
thanks for confirming. We are making some changes to the gauge launcher. Is it ok if I request you to install a pre-release (once we have a build out) version and try with the latest gauge?

We've realized that there could be different reasons for the failure, and as a first step we'd like to enable some logs which can help diagnose better.

**Comment by coding-lama** [comment]
> thanks for confirming. We are making some changes to the gauge launcher. Is it ok if I request you to install a pre-release (once we have a build out) version and try with the latest gauge?
> 
> We've realized that there could be different reasons for the failure, and as a first step we'd like to enable some logs which can help diagnose better.

Yes, I will need a little help with that though, is there some guide how to instal other that by using the "gauge install <plugin>"?
Thanks

**Comment by sriv** [comment]
hi @coding-lama - gauge-java 0.7.9 has been released, please try and see if your tests work ok. 

Note: it may take upto 24 hours for the CDN to make the artifacts available.

**Comment by sriv** [comment]
Closing this, there are some findings/recommendations in https://github.com/getgauge/gauge-java/issues/455 that seem relevant.
