### ISSUE TITLE
Can't reduce the log-level using gauge-cli, idea plugin or maven-plugin

### ISSUE THREAD

**Issue by MariusSchmidt** [getgauge/gauge-java#438]
### Expected behavior
The execution of the plugin currently overwhelms my console test result output with a lot of debug output. If I call gauge with --log-level=info, the java plugin should also respect this setting for the libs it uses.

### Actual behavior
Execution spams hundred of debug lines

Testing started at 23:34 ...
/usr/local/bin/gauge run --machine-readable --hide-suggestion --simple-console --log-level=info /path/to/project/specs
23:34:38.112 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
23:34:38.115 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - Platform: MacOS
23:34:38.118 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
23:34:38.118 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - Java version: 8
23:34:38.119 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
23:34:38.119 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
23:34:38.120 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
23:34:38.120 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
23:34:38.121 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
23:34:38.121 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
23:34:38.121 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
23:34:38.121 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
23:34:38.121 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/dw/fyw6h_l51v30hm71jxqgq7qm0000gn/T (java.io.tmpdir)
23:34:38.121 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
23:34:38.122 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 3817865216 bytes
23:34:38.122 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
23:34:38.123 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
23:34:38.123 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false

[...]

### Steps to reproduce
1. Setup a project with Spec and Java
2. Run the test using Gauge CLI, IntelliJ IDEA plugin or gauge-maven plugin

### Gauge version
gauge -v
Gauge version: 1.0.8

Plugins
-------
html-report (4.0.9)
java (0.7.4) 
screenshot (0.0.1)

**Comment by zabil** [comment]
> If I call gauge with --log-level=info, the java plugin should also respect this setting for the libs it uses.

This log level is for Gauge's logging. Unfortunately, Gauge can't control the project's log level. From the logs you posted, these are logs from `io.grpc.netty.shaded.` package. Newer versions of gauge-java uses gprc. Your root logger (using slf4j) maybe set to `DEBUG`, resulting in grpc related library using that configuration. 

To solve this problem, please set the default log level of your project to`INFO` or if you just want to exclude these messages please set the default level for this specific package to `INFO`

**Comment by sriv** [comment]
- `gauge init java`
- `gauge run --machine-readable --hide-suggestion --simple-console --log-level=info` 

gives me this:

```
{"type":"suiteStart"}
{"type":"specStart","id":"/tmp/foo/specs/example.spec","name":"Specification Heading","filename":"/tmp/foo/specs/example.spec","line":1}
{"type":"scenarioStart","id":"/tmp/foo/specs/example.spec:12","parentId":"/tmp/foo/specs/example.spec","name":"Vowel counts in single word","filename":"/tmp/foo/specs/example.spec","line":12,"result":{"time":0}}
{"type":"scenarioEnd","id":"/tmp/foo/specs/example.spec:12","parentId":"/tmp/foo/specs/example.spec","name":"Vowel counts in single word","filename":"/tmp/foo/specs/example.spec","line":12,"result":{"status":"pass","time":23}}
{"type":"scenarioStart","id":"/tmp/foo/specs/example.spec:19","parentId":"/tmp/foo/specs/example.spec","name":"Vowel counts in multiple word","filename":"/tmp/foo/specs/example.spec","line":19,"result":{"time":0}}
{"type":"out","message":"checking 'Gauge'"}
{"type":"out","message":"checking 'Mingle'"}
{"type":"out","message":"checking 'Snap'"}
{"type":"out","message":"checking 'GoCD'"}
{"type":"out","message":"checking 'Rhythm'"}
{"type":"scenarioEnd","id":"/tmp/foo/specs/example.spec:19","parentId":"/tmp/foo/specs/example.spec","name":"Vowel counts in multiple word","filename":"/tmp/foo/specs/example.spec","line":19,"result":{"status":"pass","time":2}}
{"type":"specEnd","id":"/tmp/foo/specs/example.spec","name":"Specification Heading","filename":"/tmp/foo/specs/example.spec","line":1,"result":{"status":"pass","time":0}}
{"type":"suiteEnd","result":{"status":"pass","time":0}}
{"type":"out","message":"Successfully generated html-report to =\u003e /tmp/foo/reports/html-report/index.html"}
{"type":"out","message":""}
{"type":"out","message":"Specifications:\t1 executed\t1 passed\t0 failed\t0 skipped"}
{"type":"out","message":"Scenarios:\t2 executed\t2 passed\t0 failed\t0 skipped"}
{"type":"out","message":""}
{"type":"out","message":"Total time taken: 620ms"}
```

```
$ gauge -v
Gauge version: 1.0.8
Commit Hash: 28617ea

Plugins
-------
html-report (4.0.11)
java (0.7.7)
screenshot (0.0.1)
```
