### ISSUE TITLE
Refactoring the parameter name is causing compilation issue

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#45]
With the following spec and implementation, on renaming the parameter name one encounters compilation issue

Specification:

```markdown
Users should be able to start the game
======================================

* Refactor "me" the parameter name

User should be able to access the site
--------------------------------------
tags: join
```

Implementation:

```java
@Step("Refactor <me> the parameter name")
public void RefactorTheParameterName(String me) {
    driver.get("https://www.thoughtworks.com/");
    assertEquals(me, false);
};
```

**Comment by mahendrakariya** [comment]
@sguptatw I was able to replicate the issue on the [sample project](https://github.com/sguptatw/issue_samples/tree/master/issues) you shared.

It's not a compilation error. It's a valid exception. The parameters being passed in the step implementation methods are of type `com.sun.org.apache.xpath.internal.operations.String`. But the expected type is  `java.lang.String`. That's the reason `argument type mismatch` exception is being thrown.

**Comment by sguptatw** [comment]
the issue is that renaming the parameter is not renaming the usages inside the method. I mean shift-f6 on the spec. Rename the parameter from me to something else. Now go to the code. The java file still has usages of the old variable name "me" and hence the compilation issue

**Comment by sguptatw** [comment]
As per our discussion, this is by design. The renamed parameter is considered as a different parameter. Therefore the usage of the old parameter name has to be fixed manually to solve the compilation issue.
