### ISSUE TITLE
launcher.sh: line 205: can't create : nonexistent directory

### ISSUE THREAD

**Issue by shanzee05** [getgauge/gauge-java#454]
Getting below issue from today
[INFO] --- gauge-maven-plugin:1.4.3:execute (default-cli) @ assignment-test ---
mktemp: Invalid argument
launcher.sh: line 205: can't create : nonexistent directory
Error occurred while waiting for runner process to finish.
Error : exit status 1
Error ----------------------------------
Your Environment Information -----------
linux, 1.1.1, 6e0d83f
html-report (4.0.11), java (0.7.8), reportserver (0.2.0), screenshot (0.0.1), spectacle (0.1.4), xml-report (0.2.3)

**Comment by sriv** [comment]
possibly due to https://github.com/getgauge/gauge-java/pull/422

**Comment by sriv** [comment]
@shanzee05 - can you give us some information on what environment you are seeing this error?

if it's docker - would you be able to share the image used?

if it's a desktop/vm - what distro are you on?

you can run `cat /etc/*-release` to get the above information. Thanks.

**Comment by shanzee05** [comment]
Can't share the image , its alpine base image and other dependencies are installed on top of it .

bash-5.0# cat /etc/*-release
3.11.3
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.3
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

**Comment by zabil** [comment]
Unfortunately Gauge is not tested on alpine docker images. Can you try using ubuntu or debian based images?

**Comment by shanzee05** [comment]
I have been using it successfully for few months now (gauge-java 0.7.4 and gauge v1.0.8 )- faced issue only after latest updates(Gauge and gauge-java latest version)
I reverted to

**Comment by zabil** [comment]
Ok, thanks for verifying that will look into fixing this.

**Comment by sriv** [comment]
I can confirm that this is an issue with gauge-java 0.7.8 on alpine based images.

### Steps to replicate

- `docker run -it  openjdk:15-jdk-alpine3.11 /bin/sh`
- `apk --no-cache add curl`
- `curl -SsL https://downloads.gauge.org/stable | sh`
- `mkdir foo && cd $_`
- `gauge init java`
- `gauge run specs`

Running specs on this image throws:

```
# gauge run specs
Compatible version of plugin html-report not found. Installing plugin html-report...
........................
Successfully installed plugin 'html-report' version 4.0.11
Installing required plugins.
.......................
Successfully installed plugin 'screenshot' version 0.0.1
sh: 15-ea: bad number
mktemp: Invalid argument
launcher.sh: line 86: can't create : nonexistent directory
Error occurred while waiting for runner process to finish.
Error : exit status 1
Error ----------------------------------

[Gauge]
Failed to start gauge API: Error occurred while waiting for runner process to finish.
Error : exit status 1

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	linux, 1.1.1, 6e0d83f
	html-report (4.0.11), java (0.7.8), screenshot (0.0.1)
```
