### ISSUE TITLE
Gauge.writeMessage is not working

### ISSUE THREAD

**Issue by pablodcar** [getgauge/gauge-java#47]
### Expected behavior
When a message is written using [Gauge.writeMessage](http://getgauge.io/documentation/user/current/test_code/java/custom_messages_in_reports.html), it is  expected to see the message displayed in the report, inside the step/spec where the call was done.

### Actual behavior
The message is completely ignored in the report.

### Steps to reproduce
1. Write an spec with an step where Gauge.writeMessage is called. 
2. Run the spec
3. See the report

Spec:
```
Testing Specification
=====================

Specification for testing purposes
     
Testing Scenario
----------------
tags: writeMessage

* Hello World
* Fail unconditionally
```

Steps
```java
import com.thoughtworks.gauge.Gauge;
import com.thoughtworks.gauge.Step;
import org.junit.Assert;

public class MockingSteps {

    @Step("Hello World")
    public void helloWorld() {
        Assert.assertTrue("Hello World!", true);
    }

    @Step("Fail unconditionally")
    public void fail() {
        Gauge.writeMessage("I'm going to fail");
        Assert.assertTrue("Fail unconditionally", false);
    }
}
```

Execution using Maven:
```
gauge:execute -DspecsDir=specs -Denv="qa" -Dtags="writeMessage"
```

### Gauge version
```
Gauge version: 0.3.2

Plugins
-------
html-report (2.0.0)
java (0.3.4)
xml-report (0.1.2)
```

**Comment by kashishm** [comment]
I could not reproduce it on the latest Gauge version. Could you please try this on latest [Gauge 0.4.0](https://github.com/getgauge/gauge/releases/tag/v0.4.0)?

**Comment by pablodcar** [comment]
Worked, with those versions I can see the message in the reports, thanks!

```
Gauge version: 0.4.0

Plugins
-------
html-report (2.1.0)
java (0.3.4)
xml-report (0.1.2)
```

**Comment by mahendrakariya** [comment]
Awesome!

**Comment by pablodcar** [comment]
Sorry, I read the message wrong in the report, it is not working, attached is how the report is displayed, as you can see, the "I'm going to fail" message is not present.
<img width="1256" alt="writemessage" src="https://cloud.githubusercontent.com/assets/7429473/14404543/a5e5eea0-fe4f-11e5-910c-19125e02e13c.png">

**Comment by mahendrakariya** [comment]
@pablodcar I tried again with the exact code that you mentioned in the issue. It's working fine for me.
Could you please check if there is a show/hide toggle button at the end of the step and that the message is not hidden?

![image](https://cloud.githubusercontent.com/assets/2538874/14416904/037f76d4-ffcd-11e5-8920-b0d4d67e53ec.png)

**Comment by pablodcar** [comment]
Hi @mahendrakariya, thanks for looking into it. I tested it in an isolated "Gauge" project from IntelliJ and it worked as you mentioned. However, the same code in my maven-integrated project does not produce that result. 

Could the maven integration be related? Any other thing it is worth to test? Thanks

**Comment by mahendrakariya** [comment]
@pablodcar ideally, this shouldn't have anything to do with maven. However, I tried replicating the issue with a maven project. But I was unable to do so. 

Could you please confirm what is the mvn version on your machine and as well as the gauge-maven-plugin version? On my machine, maven version is 3.3.9 and gauge-maven-plugin version in my pom file is 1.1.0. I created the test project using `gauge --init java_maven`.

I have also attached the test project that I created so that you can compare it with your project.
[test.zip](https://github.com/getgauge/gauge-java/files/214302/test.zip)

**Comment by pablodcar** [comment]
It worked from your test.zip project on my environment, so I will try to isolate the problem into a minimum project where I am able to reproduce it. Thanks.

**Comment by pablodcar** [comment]
@mahendrakariya My bad, what happened was that I run it from IntelliJ, with maven plugin, where the pom file pointed to gauge-java 0.3.3, which was not the same installed globally returned by `gauge -v`. You can close the issue since it worked ok with gauge-java 0.3.4. Thanks.

**Comment by mahendrakariya** [comment]
Coool! Glad to know your problem is resolved.
