### ISSUE TITLE
Gauge Java 0.7.9 not downloading properly

### ISSUE THREAD

**Issue by mjgroppe** [getgauge/gauge-java#470]
### Expected behavior
gauge update java 
should update the gauge-java plugin to the latest version

### Actual behavior
gauge update java
errors out because the file https://github.com/getgauge/gauge-java/releases/download/v0.7.9/gauge-java-0.7.9.zip doesn't exist

### Steps to reproduce
1. gauge update java

### Gauge version
```
Run gauge -v on your system and paste the results here.
```
Gauge version: 1.1.1
Plugins
-------
html-report (4.0.12)
java (0.7.8)
screenshot (0.0.1)
spectacle (0.1.4)

**Comment by sriv** [comment]
thanks for reporting. https://github.com/getgauge/gauge-repository/pull/55 should fix this.
