### ISSUE TITLE
gauge install java is not working

### ISSUE THREAD

**Issue by bderoy** [getgauge/gauge-java#471]
### Expected behavior
gauge install java should install gauge java plugin

### Actual behavior
gauge install java is not install gauge java plugin and throw the below error.

Failed to install plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.
Failed to install plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.

### Steps to reproduce
1. Pre-requisite: Install gauge  on centos 7
gauge version
Gauge version: 1.1.1
Commit Hash: 6e0d83f

2.Run this command to install java plugin 
$gauge install java

### Gauge version
gauge version
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
No plugins found
Plugins can be installed with `gauge install {plugin-name}`

Additional information:
gauge config --list
Key                           	Value                              
------------------------------------------------------------------
gauge_templates_url           	https://templates.gauge.org        
runner_connection_timeout     	30000                              
plugin_connection_timeout     	10000                              
plugin_kill_timeout           	4000                               
runner_request_timeout        	30000                              
ide_request_timeout           	30000                              
check_updates                 	true                               
gauge_repository_url          	https://downloads.gauge.org/plugin

**Comment by sriv** [comment]
there was an issue with the download urls that's been fixed via - https://github.com/getgauge/gauge-repository/pull/55

please give it upto 24 hours for the CDN to refresh itself.

**Comment by NivedhaSenthil** [comment]
@bderoy is that working for you now ?

**Comment by bderoy** [comment]
Hi @NivedhaSenthil , Unfortunately this is not working for me at this moment. Thanks

**Comment by zabil** [comment]
This could be a problem if you centos machine goes through a proxy to access the internet. 
`gauge install java` does work now. If you are behind a proxy try setting the `HTTP_PROXY` environment variable.

**Comment by bderoy** [comment]
Thank you. It is working now.
