### ISSUE TITLE
Refactoring results in compilation error while adding a new param and param name is a keyword in java or a numeric value

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge-java#48]
Example:
Refactor the following step

```
* hello "a" 
```

**to** 

```
* hello "1"
```

results in compilation error as refactoring names the param as `1` in implementation.'

**Comment by sguptatw** [comment]
Functional test added refactor_parameter_name_to_numeric_or_keyword.spec. Please verify and close the bug accordingly.

**Comment by kashishm** [comment]
@sguptatw Can you verify that this issue is fixed?

**Comment by sguptatw** [comment]
This has to work with special characters as well

**Comment by Apoorva-GA** [comment]
@sguptatw Could you check if the issue is still relevant?
