### ISSUE TITLE
Cannot debug java project with gauge plugin

### ISSUE THREAD

**Issue by mihaela1108** [getgauge/gauge-java#483]
### Expected behavior
Debug Project Successfully

### Actual behavior
ERROR: transport error 203: timed out waiting for connection
JDWP exit error JVMTI_ERROR_NONE(0): could not connect, timeout or fatal error

### Steps to reproduce
1. Open the JAVA project in intellij and install gauge plugin
2. Debug a test
3. Error appears

### Gauge version
```
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
java (0.7.9)
screenshot (0.0.1)
xml-report (0.2.3)

```

**Comment by zabil** [comment]
Thanks for reporting this
Please refer https://github.com/getgauge/Intellij-Plugin#notice for the right pace to post this issue.
