### ISSUE TITLE
[Feature request] Integration with IoC frameworks (Guice, Dagger, PicoContainer, etc...)

### ISSUE THREAD

**Issue by bsideup** [getgauge/gauge-java#49]
Hi!

Would be great if Gauge will provide an integration with IoC frameworks, it found it very useful in Cucumber-JVM and miss it in Gauge. 

Motivation - sharing dependencies between step implementations without singletons and ugly hacks. In case of Guice - having different scopes ( Scenario, Suite )

**Comment by mahendrakariya** [comment]
Here are some examples of cucumber guice integration shared by @bsideup on gitter.
https://github.com/rapaul/cucumber-jvm-guice-examples

**Comment by boazberman** [comment]
Could you elaborate a bit more about the use cases? And perhaps attach more examples?

**Comment by apoorvam** [comment]
@bsideup @boazberman 

* With Gauge you can set the scope of objects using property `gauge_clear_state_level `. Refer [documentation](http://getgauge.io/documentation/user/current/advanced_readings/managing_environments.html#gaugeclearstatelevel) for more details.

* [Gauge with Guice](https://github.com/getgauge/gauge-guice)
[Gauge with Spring](https://github.com/getgauge/gauge-spring)
These are sample Gauge projects demonstrating the usage of IoC frameworks with Gauge. 

Does this help?

**Comment by RabihHallage** [comment]
can somebody assign this issue to me please @sriv @kashishm

**Comment by sriv** [comment]
Very strange, for some reason I am unable to look you up in asignees in this issue. I have instead assigned it to me, so that no one else picks it up. But you can proceed with this

**Comment by RabihHallage** [comment]
@sriv  allright cool!

**Comment by RabihHallage** [comment]
Hello All,
So in order to support IoC frameworks, I propose the following logic:

1. Introduce a new annotation (i.e. @CustomClassInitializer)
2. Create a new registry, ClassInitializerRegistry that will contain the new custom class intializer, by default the registry will be null (so it doesn't affect the current logic)
3. Create a new scanner, ClassInitializerScanner which on runtime is going to scan for a class annotated with @CustomClassInitializer that implements ClassInitializer interface, such instance will be stored in the corresponding registry if found otherwise the registry will be null.
4. finally, in the message dispatcher class, we set ClassInstanceManager class initializer to the value stored in the corresponding registry (either null or custom initializer set by the user).

Note that such annotation will enable Gauge users to implement there own logic, we can as well predefine vendor specific IoC support ... so what do you think guys?

**Comment by sriv** [comment]
@RabihHallage - I realized something. Looking at @apoorvam's [comment](https://github.com/getgauge/gauge-java/issues/49#issuecomment-256635674) above, we have [`ClassInstanceManager.setClassInitializer`](http://static.javadoc.io/com.thoughtworks.gauge/gauge-java/0.6.4/com/thoughtworks/gauge/ClassInstanceManager.html#setClassInitializer-com.thoughtworks.gauge.ClassInitializer-) which enables users to register their own class instance manager.

Here's an [example](https://github.com/getgauge/gauge-example-spring/blob/master/src/test/java/RegisterIOC.java#L12) with spring.

However, it may make more sense to autowire this. So my alternate proposal is:

- User implements [`ClassInitializer`](http://static.javadoc.io/com.thoughtworks.gauge/gauge-java/0.6.4/com/thoughtworks/gauge/ClassInitializer.html) interface.
- gauge-java scans for implementations of `ClassInitializer` similar to custom screenshot.
- If user defined ClassInitializer is present, use it, else use the DefaultClassInitializer.

Thoughts?

**Comment by RabihHallage** [comment]
@sriv ,
Thanks for your reply!
I took @apoorvam comment into consideration as well, what I'm proposing is the same proposal that you provided but with an additional detail, which is the annotation that can decorates a class... anyways we can go with your proposal and remove the proposed annotation.

But i think in case the user have multiple ClassInitializer implementations and he wants to keep them all but use a specific one on run time, i guess the annotation is good in such cases?

**Comment by sriv** [comment]
@RabihHallage - thanks for the followup thoughts. Yes, in the use-case of having the option to switch `ClassInitializer`s, the annotation helps. 

I am slightly concerned about the contract though. By enforcing the interface, gauge-java can be assured that there will be an `initialize` method to be invoked. I am not aware of a mechanism to enforce this via annotations in Java (Apologies, I come from a C#/Ruby background). If you have ideas then, sure!

**Comment by RabihHallage** [comment]
@sriv, we will use both, the annotation + the interface implementation.
in other words class annotated with newly introduced annotation should implement the interface as well!

**Comment by sriv** [comment]
@RabihHallage - excellent! I think that should work.

**Comment by RabihHallage** [comment]
shall we close this issue as well?

**Comment by sguptatw** [comment]
When there are multiple classes annotated with @CustomClassInitializer
we get the following error
```
Exception in thread "main" com.thoughtworks.gauge.scan.ScanningException: Only 1 class can be annotated with @CustomClassInitializer
	at com.thoughtworks.gauge.scan.CustomClassInitializerScanner.scanForInitializer(CustomClassInitializerScanner.java:28)
	at com.thoughtworks.gauge.scan.CustomClassInitializerScanner.scan(CustomClassInitializerScanner.java:16)
	at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:40)
	at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:82)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:54)
process /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java with pid 3027 quit unexpectedly. exit status 1
[ValidationError] /Users/sswaroop/work/gauge-example-spring/specs/paymentService.spec:4 Connection closed [127.0.0.1:55254] cause: EOF => 'Set debit card balance as "1000" rupees'
[ValidationError] /Users/sswaroop/work/gauge-example-spring/specs/paymentService.spec:8 write tcp 127.0.0.1:55250->127.0.0.1:55254: use of closed network connection => 'Pay amount "500" rupees'
[ValidationError] /Users/sswaroop/work/gauge-example-spring/specs/paymentService.spec:9 write tcp 127.0.0.1:55250->127.0.0.1:55254: use of closed network connection => 'Pay amount "500" rupees'
[ValidationError] /Users/sswaroop/work/gauge-example-spring/specs/paymentService.spec:13 write tcp 127.0.0.1:55250->127.0.0.1:55254: use of closed network connection => 'Fail to pay "2000" rupees'
  Failed to initialize suite datastore. Error: write tcp 127.0.0.1:55250->127.0.0.1:55254: use of closed network connection
```

**Comment by zabil** [comment]
@sriv @RabihHallage 

Sorry for crashing this party late.

> But i think in case the user have multiple ClassInitializer implementations and he wants to keep them all but use a specific one on run time, i guess the annotation is good in such cases?

Agreed, but this is a rare and strange use case. 
It's a bit non-idiomatic to use both annotation and an interface. I suggest we keep one focused on the main use case. Like we do for [screenshots](http://getgauge.github.io/documentation/user/0.1.4/test_code/java/custom_screenshots_support.html) have and interface instead of annotation. 

>  am not aware of a mechanism to enforce this via annotations in Java (Apologies, I come from a C#/Ruby background). If you have ideas then, sure!

We can using an [annotation processor](https://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/Processor.html), but let's not go there.

**Comment by RabihHallage** [comment]
hello @zabil thanks for your input.
what i mean with multiple implementations and use 1 in run time, is:
let's say a user implemented a custom initializer A, then later on he decided to create another initializer in his code base (B).
but he wants to keep both logics in his code base, but wants to use either A or B so annotation can be used as a marker to switch from A to B ....

**Comment by RabihHallage** [comment]
@sguptatw 
it is expected to throw such exception in case of multiple annotation were employed

**Comment by sguptatw** [comment]
@RabihHallage : The exception is expected, but it should not kill the runner. Kindly refer the above comment for details.

**Comment by zabil** [comment]
> but he wants to keep both logics in his code base, but wants to use either A or B so annotation can be used as a marker to switch from A to B

Yes I understood that.  However that's a code management issue. The user can choose to use comments or version control or even removing the ```implement ClassInitializerScanner``` whatever suits them. It's best we design for the runtime use case.

**Comment by RabihHallage** [comment]
@sguptatw
So in case of multiple custom initializers:
-  use the custom class initializer 
- Log a message reflecting this matter
- and continue ...? (the user might gets an error due to classes that are not injected using the custom initializer that he specified, and gauge will exit)

**Comment by RabihHallage** [comment]
@zabil allright so in other words, remove the annotation and scan from the implemented interface?

**Comment by zabil** [comment]
> allright so in other words, remove the annotation and scan from the implemented interface?

Yes. And we'll see how people use it. All apologies for the late review comment.

**Comment by RabihHallage** [comment]
@zabil changes are done, I issued a PR
