### ISSUE TITLE
@BeforeSuite and @AfterSuite run multiple times when executing tests in parallel whit java

### ISSUE THREAD

**Issue by ccrj1105** [getgauge/gauge-java#491]
### Expected behavior
When running threads in parallel @BeforeSuite and @AfterSuite should run only once

### Actual behavior
@BeforeSuite and @AfterSuite execute each time for each parallel stream

### Steps to reproduce
Jun add @AfterSuite and run tests in parallel, AfterSuite method will run multiple times

### Gauge version
```
1.1.1
```

**Comment by olejkavn** [comment]
which version of gauge-java do you use?

**Comment by ccrj1105** [comment]
@olejkavn my version of gauge-java is 0.7.3

**Comment by olejkavn** [comment]
so you should update your versions to versions with fix(0.7.9 I suppose)

**Comment by zabil** [comment]
@olejkavn is right please upgrade gauge java to 0.7.9 make sure you've also upgraded all gauge plugins in the pom.xml, gradle files if you are using any of those.

**Comment by sriv** [comment]
Also note that you will need to enable multithreading by setting `enable_multithreading=true` in your properties (or via an env variable). Without this, each stream will run in a separate process and will run the suite hooks independently.
