### ISSUE TITLE
Add support for Dependency management

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-java#5]
There should be a provision to include external libs via one of the dependency management:
- [ ] Apache Ant with Ivy
- [x] Maven
- [ ] Gradle

**Comment by prateekbaheti** [comment]
Work in progress for a [gauge maven plugin](https://github.com/getgauge/gauge-maven-plugin)

**Comment by prateekbaheti** [comment]
Maven support added via the gauge maven plugin. Pushed artifact to maven central. Closing this.
