### ISSUE TITLE
Unable to debug java maven projects

### ISSUE THREAD

**Issue by ovixeu** [getgauge/gauge-java#501]
Getting timeout connecting to java starting debug session. 
The issue was reproduced on gauge-java version 0.7.8 and 0.7.9

Reproducing steps:

1. Create a new project using command 'gauge init java_maven'
2. Tring to debug a step get the error:

```
Testing started at 10:43 AM ...
"C:\Program Files\Gauge\bin\gauge.exe" run --machine-readable --hide-suggestion --simple-console D:/Gauge/template-project/specs/example.spec

Runner Ready for Debugging
Listening for transport dt_socket at address: 57392
Error ----------------------------------

[Gauge]
Failed to start gauge API: Timed out connecting to java

Get Support ----------------------------
Docs: https://docs.gauge.org
Bugs: https://github.com/getgauge/gauge/issues
Chat: https://spectrum.chat/gauge

Your Environment Information -----------
windows, 1.1.4, c982558
html-report (4.0.12), java (0.7.9), json-report (0.3.5), screenshot (0.0.1), spectacle (0.1.4)

Process finished with exit code 1
```

gauge.log
Runner Ready for Debugging
14-09-2020 10:53:21.512 [java] [DEBUG] running - C:\Program Files\Java\jdk-14.0.1\bin\java.exe [-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=57656,timeout=25000 -Dfile.encoding=UTF-8 com.thoughtworks.gauge.GaugeRuntime --start]
14-09-2020 10:53:21.512 [java] [DEBUG] stdout/stderr is logged to logs\12988-java.exe.out
14-09-2020 10:53:22.289 [java] [INFO] Listening for transport dt_socket at address: 57656
14-09-2020 10:53:44.326 [Gauge] [CRITICAL] Failed to start gauge API: Timed out connecting to java

12988-java.exe.out
Listening for transport dt_socket at address: 57656

$ java -version
----------------
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**Comment by ovixeu** [comment]
The downgrade to gauge-java 0.7.7 helped at the moment. Waiting your updates on this issue. Opened firstly the issue [issue-1754](https://github.com/getgauge/gauge/issues/1754) thinking that is related to gauge runner. 

Thanks in advance!

**Comment by sriv** [comment]
which IDE are you facing this with?

I am using VSCode with gauge extension (version 0.0.15), on openjdk14.0.1 (same as yours) with:

```
Gauge version: 1.1.4
Commit Hash: c982558a

Plugins
-------
dotnet (0.1.7)
flash (0.0.2)
go (0.1.4)
html-report (4.0.12)
java (0.7.10)
js (2.3.12)
json-report (0.3.3)
python (0.3.10)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)
```

I am able to debug the spec, and hit a breakpoint. (Note: I use linux).

**Comment by ovixeu** [comment]
Using Windows 10

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020

with gauge plugin 0.3.21

**Comment by NivedhaSenthil** [comment]
I could debug it fine with latest version of gauge-java 0.7.10. Can you please try updating ? Also if you are still facing the issue please check for error logs in logs folder which can help us debug the issue.

**Comment by NivedhaSenthil** [comment]
@ovixeu any updates on the issue ?
