### ISSUE TITLE
error pararell execution gauge 1.1.3

### ISSUE THREAD

**Issue by ccrj1105** [getgauge/gauge-java#502]
### Expected behavior
Tell us what should happen

### Actual behavior
When running the tests in parallel

Error ----------------------------------

[java]
Error in thread 15
null
java.lang.NullPointerException
        at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:37)
        at com.thoughtworks.gauge.RunnerServiceHandler.lambda$executeStep$7(RunnerServiceHandler.java:166)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[Gauge]
java runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

### Steps to reproduce
1.
2.
3.

### Gauge version
```Your Environment Information -----------
        linux, 1.1.3, 9d3a3d5
        html-report (4.0.12), java (0.7.9), screenshot (0.0.1), xml-report (0.2.3)

Run gauge -v on your system and paste the results here.
```

**Comment by BugDiver** [comment]
@ccrj1105 Could you please try updating the `gauge-java` plugin?

**Comment by ccrj1105** [comment]
@BugDiver  yes I already did and the same error

**Comment by sriv** [comment]
- are you using gradle/maven ? if so, what is the version of gauge-java in the dependency?
- do you see the error in a fresh project? (i.e. after you do `gauge init java` and copy `example.spec` to simulate a parallel run)
- How many streams are you running in parallel?

I assume you have `enable_multithreading=true` in your project?

**Comment by NivedhaSenthil** [comment]
i could replicate it with java_maven template, even on simple execution. The same passes fine when run using gauge command.

#### Steps:
```
gauge init java_maven
mvn gauge:execute 
```  

#### Versions:
```
Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
csharp (0.10.6.nightly-2019-01-11)
dotnet (0.1.4)
flash (0.0.1)
html-report (4.0.12)
java (0.7.10)
js (2.3.12)
json-report (0.3.1)
python (0.3.10)
ruby (0.5.3)
screenshot (0.0.1)
ts (0.0.5)
xml-report (0.2.2.nightly-2018-12-11)

java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

**Comment by NivedhaSenthil** [comment]
Observation: this exception happens when a maven project is executed without compiling. 
Works fine with `mvn -q clean compile test-compile gauge:execute`
