### ISSUE TITLE
gRPC server is listening on all interfaces.

### ISSUE THREAD

**Issue by dcRUSTy** [getgauge/gauge-java#503]
### Expected behavior
gRPC should(must?) listen only on 127.0.0.1

### Actual behavior
gRPC listening on 0.0.0.0

### Gauge version
```
gauge-java 0.7.10
```

**Comment by sriv** [comment]
Thanks for raising this. This seems to be the default that [`ServerBuilder`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerBuilder.html) seems to be setting.

According to https://github.com/grpc/grpc-java/issues/5791, we should be using `NettyServerBuilder` instead. Will try and see.

**Comment by zabil** [comment]
Fixed on release https://github.com/getgauge/gauge-java/releases/tag/v0.7.12
