### ISSUE TITLE
Refactoring results in duplicate param name in method signaure, while adding a param

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge-java#52]
### Expected behavior

Should add param with param value given to refactor command.
### Steps to reproduce
1. Refactor `Vowels in English language are "" "end" "n"` to `Vowels in English language are "" "end" "n" "n1"`
2. **Expected**: `String vowelString, String argEnd, String argN, String argVowelstring`
   
   **Actual**: `String vowelString, String argEnd, String argN, String argN1`
### Gauge version

```
0.4.1
```

**Comment by Apoorva-GA** [comment]
@sguptatw please check if this is still relevant.

**Comment by sguptatw** [comment]
@Apoorva-GA : The issue still persists

**Comment by Apoorva-GA** [comment]
**Steps to reproduce**

Refactor `Vowels in English language are "" "end" "n" `to `Vowels in English language are "vowelstring" "end" "n" "n1"`

Expected: `String argVowelstring, String argEnd, String argN, String argN1`

Works fine with latest Gauge-IntelliJ nightly : 0.3.7.nightly-2017-08-18

**Comment by sguptatw** [comment]
Refactor to `Vowels in English language are "vowelstring" "end" "n1""n" "n"`. Now the parameter names generated are duplicates

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-java nightly > 31-08-17
