### ISSUE TITLE
how to iterate a ScenarioDataStore

### ISSUE THREAD

**Issue by ccrj1105** [getgauge/gauge-java#522]
to iterate over a scenario datastore in gauge version 1.1.3 and java plugin 0.7.9 I do the following

` DataStore store = DataStoreFactory.getScenarioDataStore();
 store
        .entrySet()
        .forEach(
            entry -> {
              if ((entry.getKey()).toString().contains("Item")) {
`
but this would no longer work because now i use caliber 1.1.3 and java 0.7.13 plugin and datastore scenario does not have method
`  public Set<Map.Entry<Object, Object>> entrySet() {
        return map.entrySet();
    }`

Would it be possible to add this method in the ScenarioDataStore class?
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Gauge version
```Gauge version: 1.1.3
Commit Hash: 9d3a3d5

Plugins
-------
html-report (4.0.12)
java (0.7.13)
screenshot (0.0.1)
xml-report (0.2.3)

Run gauge -v on your system and paste the results here.
```

**Comment by zabil** [comment]
There is a new `items` method in 0.7.13

```
      ScenarioDataStore.put("1", "one");
       ScenarioDataStore.put("2", "two");
       ScenarioDataStore.put("3", "three");
       ScenarioDataStore.items().forEach((k) -> System.out.println(ScenarioDataStore.get(k)));
```

Please refer this comment https://github.com/getgauge/gauge-java/pull/520#issuecomment-714514673
