### ISSUE TITLE
"Step implementation not found" error occurs even steps are there

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge-java#539]
**Describe the bug**
I have a gauge project which contains steps in **main** package. When I am executing specs it shows below error.
```
[ValidationError] C:\Users\onimalarat\IdeaProjects\MaxSoft-IntelliAPI\specs\Access Token\Get Auth Token.spec:25 Step implementation not found => 'When the user invokes the API'
[ValidationError] C:\Users\onimalarat\IdeaProjects\MaxSoft-IntelliAPI\specs\Access Token\Get Auth Token.spec:26 Step implementation not found => 'Then the status code for the request is "201"'
[ValidationError] C:\Users\onimalarat\IdeaProjects\MaxSoft-IntelliAPI\specs\Access Token\Get Auth Token.spec:27 Step implementation not found => 'And the JSON Path Assertions for the response should be equal to the following <table>'
[ValidationError] C:\Users\onimalarat\IdeaProjects\MaxSoft-IntelliAPI\specs\Access Token\Get Auth Token.spec:32 Step implementation not found => 'And save the access token in the response which is located inside the JSON Path of "$.data"'
```

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. This is the repository (https://github.com/osandadeshan/MaxSoft-IntelliAPI)
2. This repository was worked previously with gauge-java 0.7.2. Now I have updated to gauge-java 0.7.4 in pom.xml and my laptop.

**Logs**
[gauge.log](https://github.com/getgauge/gauge-java/files/5642872/gauge.log)
[api.log](https://github.com/getgauge/gauge-java/files/5642873/api.log)

**Expected behavior**
No any errors should occur when the steps are there

**Screenshots**
![image](https://user-images.githubusercontent.com/9147189/101167006-3c83dd80-365f-11eb-8f56-ce63c2b738f4.png)

**Versions:**
 - OS: Windows 10 - 64 bit
 - Java version: 1.8.0_181
 - Maven version: 3.6.1

```
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
flash (0.0.2)
html-report (4.0.10)
java (0.7.4)
js (2.3.10)
json-report (0.3.3)
reportportal (1.4.0)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)
```

**Comment by osandadeshan** [comment]
@zabil Really appreciate your support on this issue.

**Comment by osandadeshan** [comment]
After I downgrade gauge-java version to 0.7.2 in pom.xml and machine, issue resolved. I suspect the issue is in 0.7.4 version

**Comment by zabil** [comment]
@osandadeshan the latest versions of Gauge is 1.1.6 and Gauge java is 0.7.13 Please update the plugins and the pom.xml to these versions and check.

**Comment by osandadeshan** [comment]
@zabil It is working in the latest versions you have mentioned. Thank you for the support.
