### ISSUE TITLE
"Killing runner with PID:123 forcefully" when running a simple test

### ISSUE THREAD

**Issue by henri-tremblay** [getgauge/gauge-java#553]
**Describe the bug**

I am running a really simple test using AssertJ Swing

The test is successful but seems to wait for a timeout at the end (about 5 seconds).
It then stops with "Killing runner with PID:123 forcefully".

I have tried multiple permutations and I still get the error.
The JFrame should be correctly closed and disposed of.
If I launch the Main class directly, it stops as it should.
If I try the same test using cucumber, it stops nicely.

I have code a little application to help reproduce:
[henri-tremblay/gauge-java](https://github.com/henri-tremblay/gauge-java)

**To Reproduce**

1. Clone the sample application
2. Run `mvn test`. You will see the error
3. Run `test.spec` from IntelliJ. You will see the error
4. When ran from IntelliJ, the GaugeRuntime never finish and stays open

**Logs**

gauge.log
```
04-02-2021 20:23:15.797 [html-report] [DEBUG] Transformed SuiteResult to report structure
04-02-2021 20:23:15.808 [html-report] [INFO] Successfully generated html-report to => /.../gauge-java/reports/html-report/index.html
04-02-2021 20:23:15.808 [html-report] [DEBUG] Done generating HTML report using theme from /.../.gauge/plugins/html-report/4.0.12/themes/default
04-02-2021 20:23:15.808 [Gauge] [DEBUG] Sending kill message to Html Report plugin.
04-02-2021 20:23:19.816 [Gauge] [WARNING] Killing runner with PID:76768 forcefully
```

76768-java.out
```
{"logLevel":"debug","message":"multithreading is set to false"}
{"logLevel":"debug","message":"Using reflection to scan dependencies for gauge implementations..."}
{"logLevel":"debug","message":"gauge-java took 429milliseconds to load and scan. This should be less than 'runner_connection_timeout' config value."}
{"logLevel":"debug","message":"run 'gauge config runner_connection_timeout' and verify that it is < 429"}
{"logLevel":"debug","message":"starting gRPC server..."}
{"logLevel":"debug","message":"started gRPC server on port 59943"}
{"logLevel":"info","message":"Listening on port:59943"}
{"logLevel":"debug","message":"Scanning packages for steps"}
{"logLevel":"debug","message":"Comparing 'pro.tremblay.gauge.MainImplementation.test' and 'pro.tremblay.gauge.MainImplementation.test'"}
{"logLevel":"debug","message":"Found Test in current project scope."}
{"logLevel":"debug","message":"Scanning packages for hooks"}
{"logLevel":"debug","message":"Scanned steps (using static parsing + reflections): "}
{"logLevel":"debug","message":"\tTest : public void test()"}
Before
Starting app
{"logLevel":"debug","message":"Executing 'Test' using 'class pro.tremblay.gauge.MainImplementation.test"}
Test 1972296493
Dispose
After
Dispose
Dispose
```

**Expected behavior**

**Versions:**
- Gauge 1.1.7
- html-report (4.0.12)
- java (0.7.13)
- screenshot (0.0.1)
- AdoptOpenJDK 8.0.275 Hotspot
- AssertJ 3.19.0
- AssertJ Swing 3.17.1
- macOS 10.15.7

**Additional context**

Side notes that are also preventing me from using Gauge.
I can file bugs for these issues as well if needed.

- When running from IntelliJ, the test is painfully slow to start
- IntelliJ won't use the JVM of the project to run Gauge, it will use the default JVM instead
- It means I need to get `gauge_java_home` in `java.properties` which is not portable from developer to another
- I tried using `GAUGE_JAVA_HOME` as a environment variable but it's not picked up for some reason

**Comment by sriv** [comment]
Thanks for reporting this, and apologies for the delayed response. I can replicate this issue, will investigate.

The Intellij plugin is being maintained by the Jetbrains team, so please feel free to bring this to their notice. But if there's anything Gauge can do to help, we can try and make necessary changes.

**Comment by henri-tremblay** [comment]
From my debugging, it looked like the Gauge main process was not talking correctly to the forked Java process. I'm not sure it's related to IntelliJ. But I will reach out to them.

**Comment by sriv** [comment]
Sorry, I might have been unclear. This issue of gauge having to forcefully kill runner is definitely an issue with gauge/gauge-java. I am investigating this.

I meant for you to seek advice from the Intellij team regarding the best way to.get IDEA to.pick the.right JVM version which you mentioned in the last part of this issue

**Comment by henri-tremblay** [comment]
Great. Thanks. I will report accordingly
