### ISSUE TITLE
Code lens are not showing for Gradle project having dependent module

### ISSUE THREAD

**Issue by preetipadalia** [getgauge/gauge-java#555]
**Describe the bug**
Code lens are not showing for Gradle project having dependent module.
I have two modules in my project. 
1. Core module
2. Test module
Test is dependent on Core.

Gauge specs are available in Test module. When i am opening the project in VSCODE the code lens are not showing. The logs shows it did not find the dependencies from the dependent module.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Create a gradle project
2. Add two modules
3. create the gauge project in one module and add the other module dependency
5. See error

**Logs**

```
**dependent library error logs**
10-02-2021 16:43:56.300 [Gauge] [ERROR] Error occurred while waiting for runner process to finish.
Error : exit status 1
10-02-2021 16:43:56.300 [Gauge] [DEBUG] Gauge could not initialize. Install 'vscjava.vscode-java-pack' extension for code insights. For more information see[Problems](command:workbench.actions.view.problems), check logs.[Troubleshooting](https://docs.gauge.org/troubleshooting.html?language=javascript&ide=vscode#gauge-could-not-initialize-for-more-information-see-problems)
Some of the gauge lsp feature will not work as expected.
10-02-2021 16:43:56.300 [Gauge] [INFO] LangServer: reading on stdin, writing on stdout
10-02-2021 16:43:56.305 [Gauge] [ERROR] notif #0: initialized: current runner is not compatible with gauge LSP
```

**Expected behavior**
It should work as expected

**Versions:**
 - OS [e.g. 10.15.6 (19G2021) please be specific ]
 - Java version
 ```
     openjdk version "11.0.10" 2021-01-19 LTS
     OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
     OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```
 - Maven/Gradle version
 
  ```
  ------------------------------------------------------------
   Gradle 6.8.2
------------------------------------------------------------

Build time:   2021-02-05 12:53:00 UTC
Revision:     b9bd4a5c6026ac52f690eaf2829ee26563cad426

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (Amazon.com Inc. 11.0.10+9-LTS)
OS:           Mac OS X 10.15.7 x86_64
```

```
Gauge version: 1.1.7
Commit Hash: 5d86b72

Plugins
-------
html-report (4.0.12)
java (0.7.13)
js (2.3.15)
reportportal (1.11.1)
screenshot (0.0.1)
spectacle (0.1.4)
```

**Comment by preetipadalia** [comment]
Any update on thi?

**Comment by preetipadalia** [comment]
Any update on this please?

**Comment by preetipadalia** [comment]
Can any one please provide update on this?

**Comment by zabil** [comment]
Can you please share a sample github project with the structure you described?

**Comment by preetipadalia** [comment]
Hi @zabil ,

PFA the sample project.
[SampleTest.zip](https://github.com/getgauge/gauge-java/files/6182518/SampleTest.zip)

**Comment by zabil** [comment]
If you don't mind can you share this as a public github repository? 
It will be much easier to suggest changes, point to source code and ask questions about it.

**Comment by preetipadalia** [comment]
Hi @zabil Please find below the link of github repo:

https://github.com/preetipadalia/SampleTestGradleGauge


Thanks
Preeti

**Comment by zabil** [comment]
Importing and running this project points to an issue with VS Code on MacOS Big Sur. This is mostly related to changed configuration of the JDK. So I had to manually set the right java home. More info about that here https://github.com/redhat-developer/vscode-java/issues/1700#issuecomment-729478810

Please check your "Problems" tab on VS Code to find the issues. If those issues are related to JDK configuration and setting please try to resolve that.

**Comment by preetipadalia** [comment]
Hi @zabil , I am not seeing any issues in Problems tab. PFA the screenshot for your reference.
<img width="1308" alt="Screenshot 2021-03-24 at 5 01 50 PM" src="https://user-images.githubusercontent.com/36397242/112303832-c618f300-8cc2-11eb-9875-23c54d78716a.png">

**Comment by preetipadalia** [comment]
If I convert the same project to maven project it will work but with gradle it doesn't work.
