### ISSUE TITLE
Refactor step changes special UTF-8 character to invalid character (ü to Ã¼)

### ISSUE THREAD

**Issue by kupna** [getgauge/gauge-java#64]
When I refactor a step in a spec file where special UTF-8 characters like ü are used, after refactoring they are changed to invalid characters like Ã¼

![image](https://cloud.githubusercontent.com/assets/12813719/16979049/59c5d534-4e5f-11e6-8195-b210a04d0432.png)

**Comment by kupna** [comment]
when will you fix this?

**Comment by kashishm** [comment]
This issue was moved to getgauge/Intellij-Plugin#202
