### ISSUE TITLE
Command execution problem with 2 tags (TagA & TagB or TagA,TagB)

### ISSUE THREAD

**Issue by zbrea** [getgauge/gauge-java#640]
**Describe the bug**

When I run the command "gauge run"  with the "search & successful" or "search,successful" , I receive the message No specifications found, although it works fine with the "search | successful" .
I don't know what is causing the problem?

**To Reproduce**

I run the following command  for  the example template java:
```
$ gauge run -- "search & successful" specs
```
![spec](https://user-images.githubusercontent.com/59898499/144765997-6cbeb572-4ad2-491a-a8fb-60235e3e3c7d.PNG)

**Expected behavior**

![gauge](https://user-images.githubusercontent.com/59898499/144766709-236466b0-9a47-46b4-a863-52f4a2439300.PNG)

**Versions gauge and java:**

![version](https://user-images.githubusercontent.com/59898499/144766711-23aaf5f7-6522-47b2-89bb-334cf9e11b4f.PNG)

**Comment by zabil** [comment]
> When I run the command "gauge run" with the "search & successful" or "search,successful"

This expression translates to "Run all specifications have are tagged with both `search` and `successful`. In the screenshots you posted it skips the scenario as they only one of these tags are there.

Try changing the tags to 

```
tags: search, successful
```
