### ISSUE TITLE
How does extract concept in IntelliJ Idea work?

### ISSUE THREAD

**Issue by kupna** [getgauge/gauge-java#65]
Function extract to concept should work in IntelliJ Idea?

you can find hints on this 
here [http://getgauge.io/documentation/technical/current/ide_plugin.html#extract-to-concept](http://getgauge.io/documentation/technical/current/ide_plugin.html#extract-to-concept)
and here [http://getgauge.io/documentation/user/0.0.6/ide_support/features.html](http://getgauge.io/documentation/user/0.0.6/ide_support/features.html)

How do I do it?

### Gauge version
Gauge version: 0.6.1

Plugins
-------
html-report (2.1.1)
java (0.5.0)

IntelliJ Idea Gauge Plugin
Version 0.2.3

**Comment by kupna** [comment]
any advice?

**Comment by sguptatw** [comment]
@kupna : Thanks for pointing out that the document needs to be updated.

Meanwhile here are the steps.
**Steps to extract concept**
* Open a spec
* Select the steps to be extracted.
* Right click -> Refactor -> Extract to Concept will initiate the process
* Give a concept name
* enter the file name for extraction. 
* Choose an existing concept or specify the location for new file

>Note: Currently may need to specify the extension .cpt. For the location you can use a existing folder under specs.

Hope this helps.

**Comment by mahendrakariya** [comment]
@kupna This feature is not yet released. It's still a WIP.

**Comment by kashishm** [comment]
Please refer https://github.com/getgauge/gauge/issues/508 for more info on extract to concept feature.
