### ISSUE TITLE
Windows-1252 character converted to invalid character (Ù to �)

### ISSUE THREAD

**Issue by saritapol13** [getgauge/gauge-java#67]
### Expected behavior

Test step is having parameter value as "ÙÚÛÜ ÝÞßàáâãäåæçèéêëìíîïðñòóô1" and same value should be accepted while execution
### Actual behavior

All the windows-1252 characters are converted into invalid characters
Item '���� ������������������������1' does not exist
### Steps to reproduce
1. You can trying inputing this value "ÙÚÛÜ ÝÞßàáâãäåæçèéêëìíîïðñòóô1" to any input field

We tried running through the console and even through the IntelliJ still same issue.
I tried putting value as -Dfile.encoding="windows-1252" in java.properties still no success
### Gauge version

Gauge version: 0.6.2.nightly-2016-07-31
## Plugins

html-report (2.2.0.nightly-2016-08-10)
java (0.5.2)

**Comment by boazberman** [comment]
+1 for windows-1255

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.
