### ISSUE TITLE
error while marshaling: string field contains invalid UTF-8

### ISSUE THREAD

**Issue by xwinie** [getgauge/gauge-java#678]
**Describe the bug**

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialise a gauge project
2. Use the following piece of code
3. Run the gauge command
5. See error

```
$ gauge init java
$ gauge run specs
```

**Logs**

```
Paste any log or error messages here
```

**Expected behavior**

**Screenshots**

**Versions:**
 - OS [e.g. 10.15.6 (19G2021) please be specific ]
 - Java version
 - Maven/Gradle version

```
gauge -v
```
![image](https://user-images.githubusercontent.com/3609288/156863745-1c8d2ecb-1b23-4e7e-a031-d8a8fbe61ecd.png)

**Additional context**

**Comment by sriv** [comment]
looks like there is an issue reading the csv file.
