### ISSUE TITLE
Spec tags are case sensitive

### ISSUE THREAD

**Issue by saritapol13** [getgauge/gauge-java#68]
### Expected behavior
Specs should be picked irrespective of case of tag names. Tags should be case insensitive

### Actual behavior
Tags are case sensitive and are not picked if they dont match exactly.

### Steps to reproduce
1. Have 1 spec with tag as "sandbox" and other spec as "Sandbox".
2. Run specs having tag "sandbox" from console
3. Only 1 spec is picked which is matching the exact case and word

### Gauge version
Gauge version: 0.6.2.nightly-2016-07-31

Plugins
-------
html-report (2.2.0.nightly-2016-08-10)
java (0.5.2)

**Comment by mahendrakariya** [comment]
Case sensitiveness in tags is by design. Gauge allows users to write specs in any UTF-8 supported language. It does not bother about the locale/language. Making it case insensitive might not make sense in non-latin languages, hence this decision was made to match tags exactly.
