### ISSUE TITLE
Failed to update gauge-java to latest version 0.9.0

### ISSUE THREAD

**Issue by zbrea** [getgauge/gauge-java#686]
**I can't update gauge-java to the latest gauge-java-0.9.0 for windows.x86_64**

![image](https://user-images.githubusercontent.com/59898499/163710517-22d489a6-91c6-4edd-aa78-876df841398c.png)

![image](https://user-images.githubusercontent.com/59898499/163710722-740e31e4-f30a-469d-910c-fd1127142924.png)

**Comment by zbrea** [comment]
I was able to build the build from the source by following the process described in the README.md

**Comment by zabil** [comment]
Thanks for pointing this out. There's been a problem with publishing the 0.9.0 jar files. Will be fixing this soon.

**Comment by preetipadalia** [comment]
Is there any update on this?

**Comment by sriv** [comment]
gauge-java 0.9.0 is now available and can be installed using `gauge install java` - https://github.com/getgauge/gauge-java/releases/tag/v0.9.0
