### ISSUE TITLE
install java plugin command not working

### ISSUE THREAD

**Issue by andrumacgiollari** [getgauge/gauge-java#692]
### Expected behavior
when I execute:
       gauge install java 
the plugin should install

### Actual behavior

root@67ffad305d3a:/# gauge install java
Failed to install plugin 'java'.
Reason: Invalid plugin name or there's a network issue while fetching plugin details.
root@67ffad305d3a:/#
root@67ffad305d3a:/#
root@67ffad305d3a:/# gauge install java --version 0.9.1
........................
Successfully installed plugin 'java' version 0.9.1
root@67ffad305d3a:/#

### Steps to reproduce
run gauge install java

### Gauge version

root@67ffad305d3a:/# gauge --version
Gauge version: 1.4.1
Commit Hash: a82478a

Plugins
-------
html-report (4.1.4)
java (0.9.1)
screenshot (0.1.0)
xml-report (0.2.3)
root@67ffad305d3a:/#

**Comment by zabil** [comment]
Works for me at the moment.

```
gauge install java
........................
Successfully installed plugin 'java' version 0.9.1
```

Can you please try running

```
gauge install java --log-level=debug
```

Also information on about the OS will help.
