### ISSUE TITLE
Add/execute Steps and sceanarios at Runtime

### ISSUE THREAD

**Issue by youssefMansour** [getgauge/gauge-java#693]
### Expected behavior
I want add/execute Steps and sceanarios at Runtime.

### Actual behavior
I do not know if you support this feature.

### Steps to reproduce
1.load steps/scenarios from db 
2. run those  steps/scenarios.

### Gauge version
0.71
Run gauge -v on your system and paste the results here.
0.71

**Comment by chadlwilson** [comment]
This is not really within the scope/design of gauge (and would need support in the wider project, not just for java)
