### ISSUE TITLE
Allow enums as step parameters

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge-java#70]
### Request

I would like to have the ability to have an enum in a step. Say that I have the following enum:

```
public enum ShirtColor {
    RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE;
}
```

I would like to create a step that only allows these options:

```
    @Step("Buy a <color> shirt")
    public void buyAShirt(ShirtColor myColor) {
        // Implementation goes here
    }
```

So in a spec, `* Buy a "GREEN" shirt` is allowed, but `* Buy a "BROWN" shirt` is not.
### Current behavior

There are no validation errors with `* Buy a "GREEN" shirt` or `* Buy a "BROWN" shirt`. When running the spec, the following error appears:

```
Failed Step: Pick color "GREEN"
Specification: specs\example.spec:41
Error Message: java.lang.IllegalArgumentException: argument type mismatch
Stacktrace: 
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:497)
com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:31)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:94)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:77)
com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:58)
com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:42)
com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:31)
com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:34)
com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:72)
com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)
```
### Desired behavior

I would like to have one of the following two options:
- A validation error (i.e. the red squiggly lines) underneath the word "BROWN" in `* Buy a "BROWN" shirt`
- A runtime error such as the following: `BROWN is not an enum value of ShirtColor`

It would also be a plus to be able to use `toString()` values or some other means of identifying an enum, rather than its value (so some way that "green" could be an acceptable parameter in this case).

**Comment by apoorvam** [comment]
This feature is implemented by @boazberman in this [PR](https://github.com/getgauge/gauge-java/pull/72) and is merged. 

@sguptatw Fix should be available in nightly >= 24.10.2016

**Comment by sguptatw** [comment]
Test case failing with params
```
# Buy

##Clothes
* Buy a "red" shirt

##Another
* Buy a "" shirt
```

**Comment by boazberman** [comment]
@sguptatw Hey I added the requested support in failing cases. Would love if you can approve it now ;)

**Comment by sguptatw** [comment]
@boazberman: Thanks for your interest in this feature. We are looking into the PR, will update you regarding this soon.

**Comment by boazberman** [comment]
Please notice that #75 was merged. Would love to see a version containing this feature rolling out. Any more urgent issues concerning this feature to resolve before it can be released? Please let me know!

**Comment by sguptatw** [comment]
Steps with parameter enum and ContinueOnFailure configuration is not working as expected. The corresponding issue is [here](https://github.com/getgauge/gauge/issues/528)

**Comment by mahendrakariya** [comment]
@sguptatw Both the issues that you have mentioned above aren't applicable in this case. I feel this particular issue can be closed.

**Comment by apoorvam** [comment]
Gauge-Java 0.5.1 is released with this feature! 
Run `gauge --update java` to update java plugin.
