### ISSUE TITLE
Refactoring with an enum is giving unexpected compilation errors

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#73]
**Expected behavior**
Even with the enum definition, refactoring should not give a compilation error

**Actual behavior**
After refactoring getting a compilation error

**Steps to replicate**
1. Create an implementation

```

    public enum ShirtColor  {
        RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE
    }

@Step("sdf <sdf>sdfs")
    public void implementation2(Object arg0) {
    }
```
1. Create a spec

```
Specification Heading
================
Scenario Heading
----------------
* sdf "sdf"sdfs
```
1. Refactor the step 
   `sdf "sdf"sdfs`. Then goto the code. you will see the compilation errors.

**Version**

```
Gauge version: 0.6.3.nightly-2016-10-25

Plugins
-------
csharp (0.9.2.nightly-2016-09-14)
html-report (2.2.0.nightly-2016-10-07)
java (0.5.1.nightly-2016-10-21)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by Apoorva-GA** [comment]
Issue is not replicable in latest Gauge-IntelliJ nightly : 0.3.7.nightly-2017-08-18.
