### ISSUE TITLE
Compile gauge-java for Java 17

### ISSUE THREAD

**Issue by levitin** [getgauge/gauge-java#775]
In order to utilize modern libraries in combination with gauge, compiled only for Java 17, gauge-java needs to be compiled for Java 17 as well.

**Comment by haroon-sheikh** [comment]
Hi @levitin, do you have any examples that's causing a conflict. I'm personally using gauge-java within a java21 project with no problems.

**Comment by chadlwilson** [comment]
Closing as no response :-) Can re-open if more clarity is given.
