### ISSUE TITLE
gauge install java plugin failing looks like the plugin download url is down

### ISSUE THREAD

**Issue by pcnithin** [getgauge/gauge-java#781]
Not able to install gauge java or any supported plugins
gauge version 1.6.2 or later 1.6.3 not able to install plugins.

C:\>gauge -v
Gauge version: 1.6.3
Commit Hash: 44ebad3

Plugins
-------
No plugins found
Plugins can be installed with `gauge install {plugin-name}`

C:\>gauge config --list
Key                             Value
------------------------------------------------------------------
allow_insecure_download      false
check_updates                       true
gauge_repository_url            https://downloads.gauge.org/plugin
ide_request_timeout             30000
plugin_connection_timeout  10000
plugin_kill_timeout                4000
runner_connection_timeout  30000
runner_request_timeout        30000

C:\>gauge install java
**Failed to install plugin 'java'.
Reason: Invalid plugin name or there's a network issue while fetching plugin details.**

C:\>gauge init java
Initializing template from https://github.com/getgauge/template-java/releases/latest/download/java.zip
Error ----------------------------------

[Gauge]
Failed to initialize project. Get "https://github.com/getgauge/template-java/releases/latest/download/java.zip": dial tcp 140.82.112.4:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Please use a valid Gauge template URI or check network connection

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
        windows, 1.6.3, 44ebad3
        Could not retrieve plugin information.

```

**Comment by zabil** [comment]
Worked for me just now

```
gauge install java                                                                                                                             08:41:43
........................
Successfully installed plugin 'java' version 0.10.3
⋊> ~/p/launchpad-automated on LPAUT-591/reserve-orderline-open-direct  gauge -v                                                                                                                                       08:41:55
Gauge version: 1.6.3
Plugins
-------
dotnet (0.5.0)
html-report (4.1.2)
java (0.10.3)
js (2.4.0)
python (0.3.17)
screenshot (0.1.0)
ts (0.1.0)
```

Can you please check if there's a issue with your network, or check if you are behind a proxy?

**Comment by zabil** [comment]
If you are using a proxy please refer

https://docs.gauge.org/configuration.html?os=macos&language=javascript&ide=vscode#http-proxy-setting-while-using-gauge
