### ISSUE TITLE
Specs batch run is completely marked as a failure when certain included specs have a parsing error.

### ISSUE THREAD

**Issue by gauravch12** [getgauge/gauge-java#79]
I have a batch of 80 specs to be executed. The execution fails completely if 1 or 2 specs have parsing error in them.

**Expected behavior**
In such situation, the specs that have parsing error should be skipped or marked failure with the parsing error and the rest of the batch should complete execution.
The cases that I have are
	1) tags line was pasted twice in a spec
	2) An underscore was added to a step due to a mishap.

**Actual behavior**
The complete batch of 80 specs is not executed because of some specs having parsing error.

### Gauge version
Gauge version: 0.7.1
Plugins
html-report (3.0.1)
java (0.5.2)

**Comment by sriv** [comment]
This needs to be implemented in Gauge Core. Related issue: https://github.com/getgauge/gauge/issues/532

**Comment by Apoorva-GA** [comment]
Issue https://github.com/getgauge/gauge/issues/532 is fixed in Gauge Core. There by fixing the above issue.
