### ISSUE TITLE
Failed to take custom screenshot On gauge-java

### ISSUE THREAD

**Issue by sreejitheday** [getgauge/gauge-java#87]
### Expected behaviour
Expected to take the selenium screenshot using the custom screenshot class.
public class CustomScreenGrabber implements ICustomScreenshotGrabber {
    public byte[] takeScreenshot() {
        WebDriver driver = BasePage.browser;

        Gauge.writeMessage("Failed URL: " + driver.getCurrentUrl());
        return ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
    }
}
### Actual behaviour
Custom screenshot failed and always taking regular screenshot. Getting the following error on console

[2017-04-17 18:27:59:430] [Thread-1] INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
[2017-04-17 18:28:02:517] [Thread-1] INFO BrowserManager - Latest version of [chromedriver] is 2.29
[2017-04-17 18:28:02:518] [Thread-1] INFO BrowserManager - Exporting webdriver.chrome.driver as /Users/sreejith/.m2/repository/webdriver/chromedriver/mac64/2.29/chromedriver
Starting ChromeDriver 2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b) on port 15856
Only local connections are allowed.
Apr 17, 2017 6:28:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[14.606][SEVERE]: Timed out receiving message from renderer: 1.000
[14.636][SEVERE]: Timed out receiving message from renderer: -0.031
set the timeout as 1 second
[15.641][SEVERE]: Timed out receiving message from renderer: 1.000
[15.643][SEVERE]: Timed out receiving message from renderer: -0.003
[16.648][SEVERE]: Timed out receiving message from renderer: 1.000
[16.650][SEVERE]: Timed out receiving message from renderer: -0.003
Failed to take Custom screenshot: com.gurutest.core.CustomScreenGrabber : timeout
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.01 seconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'Admins-MacBook-Pro-5.local', ip: '10.41.121.160', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b), userDataDir=/var/folders/gs/9d9qw7f549b0hykhnfr3dt_00000gp/T/.org.chromium.Chromium.8fGbzD}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=57.0.2987.133, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 00130481bd7b3bece51d91302f238795
Capturing regular screenshot..

### Steps to reproduce
1. Add CustomScreenGrabber implements ICustomScreenshotGrabber class to your automation
2. Run a test case which should fail
3. Verify the screenshot taken by Gauge

### Gauge version
Gauge version: 0.8.3
Plugins
 html-report (3.1.0)
 java (0.6.2)

**Comment by sguptatw** [comment]
Working as expected in version
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
html-report (4.0.5.nightly-2018-07-25)
java (0.6.9.nightly-2018-06-29)
```
