### ISSUE TITLE
Getting an Failed to initialize scenario datastore

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge-java#88]
_From @sguptatw on April 26, 2017 5:32_

**Steps to replicate**
* Run the command from the command line
[art 2.zip](https://github.com/getgauge/gauge/files/957307/art.2.zip)

```
mvn gauge:execute -DspecsDir=specs/one -DinParallel=true
```
Getting the following error
Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:49693->127.0.0.1:49704: use of closed network connection

_Copied from original issue: getgauge/gauge#633_

**Comment by kashishm** [comment]
This is happening because the tests are running in parallel using threads and The `Gauge.writeMessage` code is not thread safe.

**Comment by RabihHallage** [comment]
@kashishm i'm not able to recreate the bug

**Comment by kashishm** [comment]
@RabihHallage It was not consistently replicable. I had already fixed this issue but didn't push the changes. It's fixed now.

@sguptatw The fix will be available in nightly >= 03/07/2017

**Comment by Apoorva-GA** [comment]
Fixed but not tested so moving the card to QA.
