### ISSUE TITLE
Override equals in Guage Table, TableRow, and TableCells

### ISSUE THREAD

**Issue by RabihHallage** [getgauge/gauge-java#91]
Hello,
It would be a great addition if such objects contains equals.

**Comment by RabihHallage** [comment]
So guys what do you think about this?
Shall we define the equals operator for each object?

**Comment by kashishm** [comment]
@RabihHallage Thanks for bringing this up. We should be overriding `hashCode` and `equals` methods. Would you like to take a stab at it and submit a pull request?

**Comment by RabihHallage** [comment]
allright @kashishm !

**Comment by RabihHallage** [comment]
@kashishm can you please assign the issue to me.

Now for the equal operator, i can propose two definitions:
Definition A)
We say Table A equals Table B, 
	iff, 
		Table A's Headers order should  be the same for Table B, 
		AND Headers total number of A and B should be the Same
		AND Headers values should match as well
		
		AND Table A total row size should be equal to Table B total row size
		AND for any given index Y, the row at index Y in Table A should match the row at index Y in table B
		e.g.
		
		Case 1:
		Table A:						IS NOT EQUAL TO			Table B:
		|HEADER1 |HEADER2 |HEADER3 |							|HEADER2 |HEADER1 |HEADER3 |
		|--------+--------+--------|							|--------+--------+--------|
		|Value1a |Value1b |Value1c |							|Value1b |Value1a |Value1c |
		|Value2a |Value2b |Value2c |							|Value2b |Value2a |Value2c |
		
		Case 2:
		Table A:						IS EQUAL TO				Table B:
		|HEADER1 |HEADER2 |HEADER3 |							|HEADER1 |HEADER2 |HEADER3 |
		|--------+--------+--------|							|--------+--------+--------|
		|Value1a |Value1b |Value1c |							|Value1a |Value1b |Value1c |
		|Value2a |Value2b |Value2c |							|Value2a |Value2b |Value2c |	
		
Definition B)	
	We say Table A equals Table B, 
	iff,
		Table A's headers should match Table's B headers in total headers size, values regardless from order
		The total row size of Table A should match the total row size of Table B
		All rows in Table A should match rows in Table B regardless of the order
		e.g.
		
		Case 1:
		Table A:						IS EQUAL TO				Table B:
		|HEADER1 |HEADER2 |HEADER3 |							|HEADER2 |HEADER1 |HEADER3 |
		|--------+--------+--------|							|--------+--------+--------|
		|Value1a |Value1b |Value1c |							|Value1b |Value1a |Value1c |
		|Value2a |Value2b |Value2c |							|Value2b |Value2a |Value2c |	

		Case 2:
		Table A:						IS EQUAL TO				Table B:
		|HEADER1 |HEADER2 |HEADER3 |							|HEADER2 |HEADER1 |HEADER3 |
		|--------+--------+--------|							|--------+--------+--------|
		|Value2a |Value2b |Value2c |							|Value1b |Value1a |Value1c |
		|Value1a |Value1b |Value1c |							|Value2b |Value2a |Value2c |		

		Case 3:
		Table A:						IS NOT EQUAL TO			Table B:
		|HEADER1 |HEADER2 |HEADER3 |							|HEADER1 |HEADER2 |HEADER3 |Header 4|
		|--------+--------+--------|							|--------+--------+--------|--------|
		|Value1a |Value1b |Value1c |							|Value1a |Value1b |Value1c |X		|
		|Value2a |Value2b |Value2c |							|Value2a |Value2b |Value2c |Y		|		

		Case 4:
		Table A:						IS NOT EQUAL TO		 	Table B:
		|HEADER1 |HEADER2 |HEADER3 |							|HEADER1 |HEADER2 |HEADER3 |
		|--------+--------+--------|							|--------+--------+--------|
		|Value1a |Value1b |Value1c |							|Value1a |Value1b |Value1c |
		|Value2a |Value2b |Value2c |							|Value2a |Value2b |Value2c |			
		|Value3a |Value3b |Value3c |
		
So what do you think ?

**Comment by sriv** [comment]
Hi @RabihHallage ,

While I do like **definition B**, it will break the [`Table.getColumnValues(int columnIndex)`](https://github.com/getgauge/gauge-java/blob/master/src/main/java/com/thoughtworks/gauge/Table.java#L113) API. 

So I guess we should go with Definition A, where the column order is important, since we support index based lookup.

Thanks for putting this together!

**Comment by kashishm** [comment]
> Definition A)
We say Table A equals Table B,
iff,
Table A's Headers order should be the same for Table B,
AND Headers total number of A and B should be the Same
AND Headers values should match as well
AND Table A total row size should be equal to Table B total row size
AND for any given index Y, the row at index Y in Table A should match the row at index Y in table B

@RabihHallage I like the definition A and wanted to suggest changes in the order of condition checks.

* Length of Headers should be equal.
* Length of rows should be equal.
* The headers should be same in both the tables.
* The rows should be same in both the tables.

If any of the conditions fail, it should return `false` and should not check the other conditions.

Let me know your thoughts about this.

**Comment by RabihHallage** [comment]
Thanks @kashishm for your reply, the changes that you mentioned are included in the pull request that I issued earlier.
My changes are ready to be checked please review my changes and let me know if changes are needed.

**Comment by RabihHallage** [comment]
shall we close this issue?
